### ISSUE TITLE
Error repairing database

### ISSUE THREAD

**Issue by VaticanUK** [ChuckPa/PlexDBRepair#100]
Seems to be the same issue as #48, but apparently I have no valid backups 😬

Exporting current databases using timestamp: 2023-10-08_10.56.59
Exporting Main DB
Exporting Blobs DB
Successfully exported the main and blobs databases.  Proceeding to import into new databases.
Importing Main DB.
Importing Blobs DB.
Runtime error near line 49883: UNIQUE constraint failed: blobs.linked_type, blobs.linked_id, blobs.blob_type (19)
Error 1 from Plex SQLite while importing from './dbtmp/blobs.plexapp.sql-2023-10-08_10.56.59'
Cannot continue.

Could you add the modification mentioned in #48 to allow handling this situation?

Thanks

**Comment by ChuckPa** [comment]
This happens when importing on top of existing databases.

May I see a `ls -la` of the Databases directory and also know which UID & GID or username this was run as ?

```
Runtime error near line 49883: UNIQUE constraint failed: blobs.linked_type, blobs.linked_id, blobs.blob_type (19)
Error 1 from Plex SQLite while importing from './dbtmp/blobs.plexapp.sql-2023-10-08_10.56.59'
```

**Comment by VaticanUK** [comment]
Sure: 
![image](https://github.com/ChuckPa/PlexDBRepair/assets/1851814/6705120a-ea1b-4aac-9a2d-278320fde314)

I'm running this in docker, so ran `id` to get the uid and gid:
![image](https://github.com/ChuckPa/PlexDBRepair/assets/1851814/548f514b-d8bf-4493-a3a1-bf6301836e46)

`DBRepair.sh -i` seems to have done the trick though! Thanks!

**Comment by ChuckPa** [comment]
Glad you got it.
