### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by pooreboy** [ChuckPa/PlexDBRepair#111]
I see dbRepair.bat and a windows zip can i use this utility on my plex install that is running native on windows?

**Comment by ChuckPa** [comment]
Yes,  you can.

It's a simplied (due to scripting difficulties) version.

It runs the equivalent of "Automatic" optimization.

You stop Plex.   run the script.   start Plex

**Comment by ChuckPa** [comment]
DBRepair-Windows.zip now updated to contain current DBRepair-Windows.bat.

Apologies for having forgotten

**Comment by pooreboy** [comment]
No worries thanks so much I'm having some weird issues on my server but the db has been running for 8 years hoping this can help
