### ISSUE TITLE
Compatible with Plex Database changes in 1.40.0.7775 ?

### ISSUE THREAD

**Issue by Mr-Lucas** [ChuckPa/PlexDBRepair#117]
Love this utility.  It has brought my Plex server's performance back from the brink on a number of occasions after I have added/removed large quantities of content or deleted libraries.

I noticed that the the latest Plex beta indicates "this version makes changes to the database which will make it compatible only with server versions 1.31.2 or higher (released March 14). You will not be able to use your database on Plex Media Server versions lower than this after this update. Please also be patient when updating to this version if you have a very large database and allow the upgrade process to finish."  https://www.reddit.com/r/PleX/comments/18lxqgg/new_beta_pms_version_available_14007775456fbaf97/

Will this impact the use of the PlexDBRepair utility?

Thanks for such a great too1, thank you for creating/maintaining it.

**Comment by ChuckPa** [comment]
There are no known compatibility issues with the new Plex database.

The only database variables it specifically calls out are watched status.  This hasn't changed across the versions.
