### ISSUE TITLE
Recommended Scheduled Maintenance Actions? 

### ISSUE THREAD

**Issue by zhdenny** [ChuckPa/PlexDBRepair#118]
As title says, I'm wondering if there is a recommended set of actions to do regularly for maintenance purposes. And how often (daily/weekly/monthly). Like a routine Plex "oil change" sort of deal to keep it running at peak performance.

These days many people are running a lot of intense tools on Plex (Plex-Meta-Manager comes to mind but many others). Plex libraries are getting quite large as well. Plex getting sluggish/slow/corrupt is a more common occurrence.

**Comment by ChuckPa** [comment]
If you read the README,

You'll see the recommended maintenance actions on a automated mechanism:

```
DBRepair.sh   stop auto start exit
```

**Comment by zhdenny** [comment]
Thanks!
Any particular reason vacuum is not part of the recommended maintenance actions?

**Comment by ChuckPa** [comment]
Vacuum is SQLite internal only.

Export-import is better because the linked lists connecting records are rebuilt during the import.
Vacuum does not.

**Comment by zhdenny** [comment]
Thanks!
