### ISSUE TITLE
Can't run script to fix database because of Supervisor

### ISSUE THREAD

**Issue by s2-ieuan** [ChuckPa/PlexDBRepair#119]
Hello,

This is not really a bug, but more of a logic problem. I am using the official plexinc/pms-docker:plexpass image, which uses supervisor to check is Plex is running. I'm having an issue where Plex does not start, and running this script was recommended to my by someone.  
The problem I'm facing is that supervisor times out and the container reboots after a few minutes. This also means that if I run the 'stop' command, the container immediately exits, as supervisor got told to kill plex.

The kill command listed in the readme does not work for the official docker image, Plex just keeps running under the same PID.  

Is there any way to run the script on the data directory (with the container turned off)?

**Comment by s2-ieuan** [comment]
I ended up modifying the Docker image and building my own version without the health check, which allowed me to run the tool. Sadly does not seem like Plex is booting still. Oh well..

**Comment by ChuckPa** [comment]
The official Plex image has  the `/plex_service.sh` command which handles the health check.

Is that not working?

**Comment by s2-ieuan** [comment]
> The official Plex image has the `/plex_service.sh` command which handles the health check.
> 
> Is that not working?

I couldn't figure that out, but making a copy of their Dockerfile and making the health check just not `exit` worked.  

Also apparently I lied earlier, after running PlexDBRepair with my modified image and then restarting it back into the official Plex docker image it is now up and running, so thank you very much for this amazing tool!

**Comment by ChuckPa** [comment]
```
docker exec -it <container_name> bash
/plex_service.sh -d     # takes it down but keeps the container up and safe
/plex_service.sh -u     # brings plex back up
```

sorry if I don't have the names exact (hard to keep everyone's images in my head)

**Comment by s2-ieuan** [comment]
> ```
> docker exec -it <container_name> bash
> /plex_service.sh -d     # takes it down but keeps the container up and safe
> /plex_service.sh -u     # brings plex back up
> ```
> 
> a `ls` of the root will give you the name :) sorry if I don't have the names exact (hard to keep everyone's images in my head)

That is good to know for the future, thanks!
