### ISSUE TITLE
page_size changed during script runs 

### ISSUE THREAD

**Issue by mfoti** [ChuckPa/PlexDBRepair#122]
I've changed my db `page_size` to `65536` to match my filesystem record size[1] but after this script runs it is set to `4096`. 

Is it possible to don't change this value? Or have a it defined in config and set it on script run? 

```
# Page Size
PageSize=65536

PRAGMA page_size=$PageSize; VACUUM; PRAGMA page_size;
``` 

1. https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Workload%20Tuning.html#sqlite

**Comment by ChuckPa** [comment]
The script uses Plex_SQLite defaults  (safe for all platforms) because it must run everywhere without modification.

I'm planing on supporting a config file where you can set such things.
The only issue I have is the management of that config file (where to put it / where is $HOME defined? )

**Comment by mfoti** [comment]
One of the most recurring problems with PMS on large dataset is the database performance, SQLite is fine for small builds but become unstable when people have a lot of friends and more than ~10k media, moreover if PMS is overcharged with tools like PMM and the *arr suite, sooner or later users encounter into `Sqlite3: Sleeping for 200ms to retry busy DB` error. I personally added the DBRepair into cronjob removing the default optimization tool (and another tool I was using before). This helps me a lot.

But some other things can be done, this Plex forum thread is a good starting point: https://forums.plex.tv/t/suggested-sqlite3-db-optimizations/794749, changing the FS record size to 64k and moving the page_size to the same value gave me an huge performance gain, next step will be to move things in memory (temp_store=2 and mmap_size).

> I am curious, given PMS makes thousands, if not millions, of files less than 64K, why you'd put PMS on a volume with such a large size and waste that space knowing the hardware is still going to pull in the data in process memory page size bytes (4K byte pages)

I just create a dataset over ZFS for Library/..../Databases path (and it allows me to snapshot and replicate the data too). I do the same also for other software, with ZFS is very easy to manage such things. 

> The only issue I have is the management of that config file (where to put it / where is $HOME defined? ) and which parameters to allow customization of.

I usually follow KISS principles, IMO an optional parameter in file header, as argument or even in an env var is enough. Who modify usually knows what is doing, this script is very simple to make up and running and this is a good advantage. 
For me will be fantastic to to be able to do something like: `./DBRepair.sh --page_size=N --temp_store=N --mmap_size=N auto` that stops PMS, runs optimizations, start PMS and quit. And I will schedule PMM + DBRepair (optimize) to run daily

**Comment by ChuckPa** [comment]
How does this strike you?

1.  I will document, but not advertise, the DBREPAIR_PAGESIZE environment variable
2.  If it exists and is > 0,  
  -  Add 1023 to it and force to be a multiple of 1024 (per the SQLite documentation)
  -  else skip down to step #4 below 
3.  Add tiny function which, prior to doing the big import,
  - Creates the new target db via a 'vacuum' command
  - The new page size will be specified on that command line
4. the big import will then run normally.
5. No other code will be altered.

Log of my testing looks like this:
```
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases/dbtmp# ll
total 1617632
drwxr-xr-x 2 root root       115 Jan 14 12:15 ./
drwxr-xr-x 3 plex plex      4096 Jan 14 11:59 ../
-rw-r--r-- 1 root root 533725184 Jan 14 11:34 com.plexapp.plugins.library.db
-rw-r--r-- 1 root root 561358192 Jan 14 12:14 dbdump.sql
-rwxr-xr-x 1 root root       827 Jan 14 12:11 SetPageSize*
-rw-r--r-- 1 root root 561358192 Jan 14 12:00 sql.in
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases/dbtmp# echo $PAGESIZE
65535
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases/dbtmp#  # PAGESIZE is incorrect.  Observe what happens
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases/dbtmp# ./SetPageSize 
Got Pagesize=65535
Using Pagesize=65536
dumping
Setting page size
65536
Importing
New page size is:
65536
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases/dbtmp# cat SetPageSize 
#!/bin/sh

SQLITE="/usr/lib/plexmediaserver/Plex SQLite"

# If pagesize does not exist, do nothing
[ "$PAGESIZE" = "" ] && exit

# If it does exist, confirm/force to a multiple of 1024
echo Got Pagesize=$PAGESIZE
PAGESIZE=$(expr $PAGESIZE + 1023)
PAGESIZE=$(expr $PAGESIZE / 1024)
PAGESIZE=$(expr $PAGESIZE \* 1024)
echo Using Pagesize=$PAGESIZE

[ $PAGESIZE -le 0 ] && echo PAGESIZE invalid. Exiting. && exit

# now dump
echo dumping
"$SQLITE" com.plexapp.plugins.library.db  .dump > dbdump.sql

# Create new DB
echo Setting page size
"$SQLITE" temp.plexapp.plugins.library.db "PRAGMA page_size=${PAGESIZE}; VACUUM; PRAGMA page_size;"

# Load it up
echo Importing
"$SQLITE" temp.plexapp.plugins.library.db < dbdump.sql

# Confirm page size
echo New page size is:
"$SQLITE" temp.plexapp.plugins.library.db 'PRAGMA page_size;'

root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases/dbtmp#
```

**Comment by mfoti** [comment]
great!

**Comment by ChuckPa** [comment]
Will  that satisfy the need and work for all ZFS cases ?

**Comment by mfoti** [comment]
I don't have such usage reports, I guess common plex user doesn't need this tool in most cases (recreate a corrupted db for few files is quite easy, and I guess usually them doesn't uses rating etc so no data is lost). I had it when I've tried to optimize and preserve things (and workaround the lack of a true db support in plex). ZFS I guess is not used by a lot of Plex users, but only who need advanced feature in a FS, and who need these advanced feature usually uses them. So in terms of how many people need it maybe few, how much is relevant for who looks for quality, and uses your tool, a lot. But you are the boss these are only my 2c  😅

**Comment by ChuckPa** [comment]
Most of Plex's users are Windows users.

The second most common users are NAS users.
Of those, there is a growing, but less common at this point, QNAP QuTS (ZFS) user base.

Most of the heavy duty Linux users I work with use XFS (because we know ext4 is unsafe  for large filesystems > 50TB)

To share where I'm at in writing this up  (draft) of which I need working code to document the rest:

```
# Environment Variables

  DBRepair uses environment variables to allow customization of the database operations.

  Normal Linux (ext4, xfs) filesystems do not need this customization because the filesystem block size = 4096.
  ZFS users sometimes need to customize their datasets to improve I/O performance (HDDs vs SSDs)

####  WARNING:  Use of these variables may adverse impact PMS operation or performance.  USE WITH CAUTION.

### DBREPAIR_PAGESIZE - Allows setting the SQLite 'page_size'.

  If present, sets the SQLite 'page_size' for both Main and Blobs databases.
  Otherwise, the default page size for the host OS is used (typically 4096 to match the OS page size)

  When in use, you will see the message:  "Plex SQLite:  page_size = <page_size_specified>"
  This will be shown on the console output and reported in the logfile.

#### Constraints:

    1.  Must be a multiple of 1024  (per SQLite 3.12.0 documentation)
        Any value provided willl be forced to be a multiple of 1024.

    2.  May it exceed 65536  (per SQLite 3.12.0 documentation)
        Any value exceeding 65536 will be set to 65536.

#### Usage:  (Linux shown)

  export DBREPAIR_PAGESIZE=32768
  sudo ./DBRepair.sh
```

**Comment by ChuckPa** [comment]
@mfoti 

Here is something for you to try.
I've done initial testing here and it looks good but I don't have a ZFS system to fully gauge the improvement.

Also please find the updated README.md

Your input welcome.

https://drive.google.com/file/d/1UYQfqzLa82VO11yUaalXPx1SL9G0Q0Z3/view?usp=sharing

**Comment by mfoti** [comment]
downlading

**Comment by ChuckPa** [comment]
damn you're quick!  LOL

**Comment by mfoti** [comment]
I can't run it know, I'll do it asap. Reading the code seems that there isn't any check that the value was set, I don't know if you want but you can test it with something like: 

```
  # Create DB with desired page size
  Result="$("$PLEX_SQLITE" "$1" "PRAGMA page_size=$PageSize; VACUUM; PRAGMA page_size;")"
  if [ "$Result" = $PageSize ]; then
    return 0
  else
     SQLerror="$(echo $Result | sed -e 's/.*code //')"
    return 1
  fi
```

I will update you tomorrow

**Comment by ChuckPa** [comment]
I don't need to check it was set.

I tested that as I was writing.

1.  Create empty database, with the PRAGMA, and perform VACUUM;   (this sets the page_size)
2.  Open the DB and perform INSERT INTO statements   (these do not alter the DB page_size)
3.  Checking the page_size after completion confirms the size is still set
4.

**Comment by mfoti** [comment]
With a correct usage I guess never. 

If the database is running it will not be set:

```
Plex\ SQLite com.plexapp.plugins.library.db
sqlite> PRAGMA integrity_check; PRAGMA page_size=65536; VACUUM; PRAGMA page_size;
ok
1024
```
but you do it in a backup copy so I don't see problems

If the database is corrupted it will not work:
```
sqlite> PRAGMA page_size=65536;VACUUM;
Error: no such collation sequence: icu_root
```
but you will check this before the command

So, I guess there isn't any case where this can fail. Is just a double check that can inform "I wasn't able to set the page size for this `SQLerror`" but I think it can't happens

**Comment by ChuckPa** [comment]
```
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# echo $DBREPAIR_PAGESIZE
65535
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# ./dbrdev.sh stop auto exit
 
 
 
      Plex Media Server Database Repair Utility (Ubuntu 22.04.3 LTS)
                       Version v1.02.99
 
 
[2024-01-14 17.56.16] Stopping PMS.
[2024-01-14 17.56.16] Stopped PMS.
 
[2024-01-14 17.56.16] Automatic Check,Repair,Index started.
[2024-01-14 17.56.16] 
[2024-01-14 17.56.16] Checking the PMS databases
[2024-01-14 17.57.29] Check complete.  PMS main database is OK.
[2024-01-14 17.57.29] Check complete.  PMS blobs database is OK.
[2024-01-14 17.57.29] 
[2024-01-14 17.57.29] Exporting current databases using timestamp: 2024-01-14_17.56.16
[2024-01-14 17.57.29] Exporting Main DB
[2024-01-14 17.57.40] Exporting Blobs DB
[2024-01-14 17.57.41] Successfully exported the main and blobs databases.  Proceeding to import into new databases.
[2024-01-14 17.57.41] Importing Main DB.
[2024-01-14 17.57.41] Setting Plex SQLite page size (65536)
[2024-01-14 17.58.10] Importing Blobs DB.
[2024-01-14 17.58.10] Setting Plex SQLite page size (65536)
[2024-01-14 17.58.12] Successfully imported databases.
[2024-01-14 17.58.12] Verifying databases integrity after importing.
[2024-01-14 17.59.25] Verification complete.  PMS main database is OK.
[2024-01-14 17.59.25] Verification complete.  PMS blobs database is OK.
[2024-01-14 17.59.25] Saving current databases with '-BACKUP-2024-01-14_17.56.16'
[2024-01-14 17.59.25] Making repaired databases active
[2024-01-14 17.59.25] Repair complete. Please check your library settings and contents for completeness.
[2024-01-14 17.59.25] Recommend:  Scan Files and Refresh all metadata for each library section.
[2024-01-14 17.59.25] 
[2024-01-14 17.59.25] Backing up of databases
[2024-01-14 17.59.25] Backup current databases with '-BACKUP-2024-01-14_17.59.25' timestamp.
[2024-01-14 17.59.26] Reindexing main database
[2024-01-14 17.59.49] Reindexing main database successful.
[2024-01-14 17.59.49] Reindexing blobs database
[2024-01-14 17.59.49] Reindexing blobs database successful.
[2024-01-14 17.59.49] Reindex complete.
[2024-01-14 17.59.49] Automatic Check, Repair/optimize, & Index successful.
 
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# sqlite3 com.plexapp.plugins.library.db 'PRAGMA page_size;'
65536
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# 
```

**Comment by ChuckPa** [comment]
Conclusive :) 

```
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# sqlite3 com.plexapp.plugins.library.db 'PRAGMA page_size;'
65536
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# export DBREPAIR_PAGESIZE=32768
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# ./dbrdev.sh stop auto exit
 
 
 
      Plex Media Server Database Repair Utility (Ubuntu 22.04.3 LTS)
                       Version v1.02.99
 
 
[2024-01-14 18.03.25] PMS already stopped.
 
[2024-01-14 18.03.25] Automatic Check,Repair,Index started.
[2024-01-14 18.03.25] 
[2024-01-14 18.03.25] Checking the PMS databases
[2024-01-14 18.04.38] Check complete.  PMS main database is OK.
[2024-01-14 18.04.38] Check complete.  PMS blobs database is OK.
[2024-01-14 18.04.38] 
[2024-01-14 18.04.38] Exporting current databases using timestamp: 2024-01-14_18.03.25
[2024-01-14 18.04.38] Exporting Main DB
[2024-01-14 18.04.49] Exporting Blobs DB
[2024-01-14 18.04.50] Successfully exported the main and blobs databases.  Proceeding to import into new databases.
[2024-01-14 18.04.50] Importing Main DB.
[2024-01-14 18.04.50] Setting Plex SQLite page size (32768)
[2024-01-14 18.05.20] Importing Blobs DB.
[2024-01-14 18.05.20] Setting Plex SQLite page size (32768)
[2024-01-14 18.05.20] Successfully imported databases.
[2024-01-14 18.05.20] Verifying databases integrity after importing.
[2024-01-14 18.05.33] Verification complete.  PMS main database is OK.
[2024-01-14 18.05.33] Verification complete.  PMS blobs database is OK.
[2024-01-14 18.05.33] Saving current databases with '-BACKUP-2024-01-14_18.03.25'
[2024-01-14 18.05.33] Making repaired databases active
[2024-01-14 18.05.33] Repair complete. Please check your library settings and contents for completeness.
[2024-01-14 18.05.33] Recommend:  Scan Files and Refresh all metadata for each library section.
[2024-01-14 18.05.33] 
[2024-01-14 18.05.33] Backing up of databases
[2024-01-14 18.05.33] Backup current databases with '-BACKUP-2024-01-14_18.05.33' timestamp.
[2024-01-14 18.05.33] Reindexing main database
[2024-01-14 18.05.57] Reindexing main database successful.
[2024-01-14 18.05.57] Reindexing blobs database
[2024-01-14 18.05.57] Reindexing blobs database successful.
[2024-01-14 18.05.57] Reindex complete.
[2024-01-14 18.05.57] Automatic Check, Repair/optimize, & Index successful.
 
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# sqlite3 com.plexapp.plugins.library.db 'PRAGMA page_size;'
32768
root@glockner:/vol/plexmediaserver/Plex Media Server/Plug-in Support/Databases# 
```

**Comment by ChuckPa** [comment]
It is easy to add the verification

NewPageSize="$( "$PLEX_SQLITE" "$1" 'PRAGMA page_size')"
if [ $NewPageSize -ne $DbPageSize ]; then
  Output SetPageSize "ERROR:  Unable to set page size.  Got $NewPageSize instead of $DbPageSize"
  WriteLog "SetPageSize - Error Unable to set $DbPageSize.  Got $NewPageSize instead."
fi

**Comment by mfoti** [comment]
it works! 🥳

```
Automatic Check,Repair,Index started.

Checking the PMS databases
Check complete.  PMS main database is OK.
Check complete.  PMS blobs database is OK.

Exporting current databases using timestamp: 2024-01-15_00.04.11
Exporting Main DB
Exporting Blobs DB
Successfully exported the main and blobs databases.  Proceeding to import into new databases.
Importing Main DB.
Setting Plex SQLite page size (65536)
Importing Blobs DB.
Setting Plex SQLite page size (65536)
Successfully imported databases.
Verifying databases integrity after importing.
Verification complete.  PMS main database is OK.
Verification complete.  PMS blobs database is OK.
Saving current databases with '-BACKUP-2024-01-15_00.04.11'
Making repaired databases active
Repair complete. Please check your library settings and contents for completeness.
Recommend:  Scan Files and Refresh all metadata for each library section.

Backing up of databases
Backup current databases with '-BACKUP-2024-01-15_00.07.02' timestamp.
Reindexing main database
Reindexing main database successful.
Reindexing blobs database
Reindexing blobs database successful.
Reindex complete.
Automatic Check, Repair/optimize, & Index successful.

root@99c471c833d6:~# /usr/lib/plexmediaserver/Plex\ SQLite /config/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/com.plexapp.plugins.library.blobs.db 'PRAGMA page_size;'
65536

root@99c471c833d6:~# /usr/lib/plexmediaserver/Plex\ SQLite /config/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/com.plexapp.plugins.library.db 'PRAGMA page_size;'
65536
```

**Comment by ChuckPa** [comment]
Which OS are you using?    TrueNAS or a Linux distro ?

**Comment by mfoti** [comment]
unraid

**Comment by ChuckPa** [comment]
Ah.   I have a tiny, 1-drive Unraid development NUC   hahaha

**Comment by ChuckPa** [comment]
I will publish this in my forum preview as 1.03.00.

Feel free to keep this until formally published.

**Comment by ChuckPa** [comment]
Sorry.. Forgot..  You also now have "Remove" (or "purge") menu option to clean Cache/PhotoTranscode directory

**Comment by mfoti** [comment]
wowwwww I do it with ahahahah a dirty:
```
find "/mnt/cache/appdata/Plex-Media-Server/Library/Application Support/Plex Media Server/Cache/PhotoTranscoder" -name "*.jpg" -type f -mtime +5 -delete
```

**Comment by ChuckPa** [comment]
I will eventually add an environment variable for that too!  LOL

**Comment by ChuckPa** [comment]
Will be released in 01.03.00

**Comment by ChuckPa** [comment]
I'm not a Windows developer.   I've not touched Windows in well over 10 years (and that was briefly as a user)/

The limit of my skills is writing basic BAT file sequences.

I'm sure there are folks out there who can write this in powershell but nothing has ever been completed and shared here.

**Comment by ChuckPa** [comment]
The page size adjustment works 

1. dump the entire DB to '.sql' text file.
2. creating an empty DB with the specified page_size
3. importing the previously exported SQL 

The size specified must be aligned per and within SQLite limits (their documentation)
