### ISSUE TITLE
ERROR: Cannot write to Databases directory. Insufficient privilege.

### ISSUE THREAD

**Issue by jl94x4** [ChuckPa/PlexDBRepair#125]
`root@Plexified:/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases# ./DBRepair.sh
ERROR: Cannot write to Databases directory. Insufficient privilege.`

![image](https://github.com/ChuckPa/PlexDBRepair/assets/18123855/e2d9bdab-80a4-4662-b6bb-eb5db734cd51)

For some reason, outside of the container the folders/files are owned by nobody:users but inside they are owned by abc:users?

![image](https://github.com/ChuckPa/PlexDBRepair/assets/18123855/663ac70b-f596-4310-9350-18d58399587b)

Not sure where to go next

**Comment by ChuckPa** [comment]
Check here please.

Recent issue (Rabbit hole) which was a local system issue.

https://github.com/ChuckPa/PlexDBRepair/issues/120

**Comment by ChuckPa** [comment]
Status please ?

**Comment by ChuckPa** [comment]
Closing,  assumed resolved.

**Comment by jl94x4** [comment]
Still struggling with this ive checked all perms and can't find thr issue

**Comment by jl94x4** [comment]
Can I get a little help with this I've tried everything
