### ISSUE TITLE
How to restart from scratch the DB and import the view history from a backup

### ISSUE THREAD

**Issue by Speedmod88** [ChuckPa/PlexDBRepair#131]
Its may be useless but I got some movies that's don't want to start... only newly added its work #1 but not the older one... 

Still not sure what causing my issue but I may want to delete the sql.db and do a fresh restart of my whole library to see if that could fix my issue

 I would like to know how I need to proceed without messing everything by using your 'Import' to simply import watch history to my brand new DB once done

is that instruction should be good to do it?
1. stop docker
2. delete both .db and blob.db
3. restart docker
4. open DBRepairTool -> stop Import

or that won't work like I think?

Thanks for your help and offering us this great tool :)

**Comment by ChuckPa** [comment]
If you are not seeing  DB Corruption errors in the Plex logs --  then deleting the DB is pointless.

If you want to  completely rebuild the server from scratch,  then later import the previous watch history --
1.   STOP Plex
2. COPY the com.plexapp.plugins.library.db file to someplace safe
3.  ERASE all of PMS (main storage area) & rebuild a new server instance
4.  START the tool and   IMPORT the watch history from the saved DB (you give it the path to the DB)
5.  After import is complete,   recommend optimizing the DB and getting everything aligned.

**Comment by Speedmod88** [comment]
ok awesome thank you :)
