### ISSUE TITLE
New Prune feature uses the wrong folder.

### ISSUE THREAD

**Issue by minermartijn** [ChuckPa/PlexDBRepair#133]
Im using the Hotio docker image.

Can you make it so i can set a variable to set the correct prune folder?

`find: ‘/config/Plex Media Server/Cache/PhotoTranscoder’: No such file or directory`

But my config folder on docker is already linked to the Plex Media Server folder.
So it should be /config/Cache/PhotoTranscoder

**Comment by ChuckPa** [comment]
DBRepair is using the correct directory ($APPSuppDir/Plex Media Server/Cache)  but HOTIO isn't using standard.

I'll schedule this to see what can be done.

**Comment by ChuckPa** [comment]
The solution for this is to add your own secondary to deal with HOTIO being non-standard
