### ISSUE TITLE
Cannot write to databases folder

### ISSUE THREAD

**Issue by jl94x4** [ChuckPa/PlexDBRepair#134]
https://github.com/ChuckPa/PlexDBRepair/issues/125

Still struggling with this can I get a little help?

**Comment by jl94x4** [comment]
Inside the container

![image](https://github.com/ChuckPa/PlexDBRepair/assets/18123855/18fbe7d3-11b9-41c4-bce0-0d616ab73693)

Outside the container

![image](https://github.com/ChuckPa/PlexDBRepair/assets/18123855/13a14da9-628a-4b42-9215-cfd4766de5fd)

**Comment by ChuckPa** [comment]
This is only the 2nd reported case of this happening.

The first known case is as I shared with you.
I know it's something to do with how your container is created but don't know how to debug the container and mapping itself.

The first / only issue was because DOCKER_MODS changed how the mapping worked even though the numbers LOOKED the same.

**Comment by jl94x4** [comment]
My docker container

``docker run
  -d
  --name='plex-1-1'
  --net='host'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Plexified"
  -e HOST_CONTAINERNAME="plex-1-1"
  -e 'VERSION'='docker'
  -e 'PLEX_CLAIM'=''
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:32400]/web/index.html'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/plex-logo.png'
  -v '/mnt/ssd/plexified/mounts/secret':'/var/lib/plexmediaserver/Library/secret':'rw'
  -v '/mnt/nvme/plexified/docker/plex':'/mnt/nvme/plexified/docker/plex':'rw'
  -v '/mnt/nvme/plexified/docker/plex/':'/config':'rw' 'lscr.io/linuxserver/plex:latest'
36e763bff513bf57e23e613e2a2c741edb122139d186442d837cdb563219e48f``

**Comment by ChuckPa** [comment]
please come to the plex forums.


This sounds more like a core PMS 1.40 issue and not a DBRepair tool issue.

**Comment by ChuckPa** [comment]
I'm  currently testing PMS.   As soon as the machine is available,  I'lll boot unraid and walk the path through the filesystem.

From there, I'll give you the info I find.

**Comment by jl94x4** [comment]
> I'm currently testing PMS. As soon as the machine is available, I'lll boot unraid and walk the path through the filesystem.
> 
> From there, I'll give you the info I find.

Thank you, I would appreciate that!
