### ISSUE TITLE
Best practice for IGNORE parameter?

### ISSUE THREAD

**Issue by liquid-ion** [ChuckPa/PlexDBRepair#135]
Had a bad database before the IGNORE function was added. 

AUTO

reported a unique constraint issue, and couldn't complete the REPAIR. I instead used REPLACE and recovered a backup from a few days prior.

1) Had I used this newer version, could I have instead turned on IGNORE when I saw the unique constraint issue, then rerun AUTO?

2) I noticed IGNORE mentions that a bad database will never be created. Should this be used anytime a unique constraint error is encountered? 

3) Is there any downside to using IGNORE when a unique constraint issue is encountered or is there a better way to fix?

Thanks

**Comment by ChuckPa** [comment]
The intent of IGNORE is for CONSTRAINT errors.

The use case is importing watch history from another DB into the active DB.
There will always be overlapping ID numbers because they are auto-increment starting at 1.
