### ISSUE TITLE
macOS cache directory incorrect

### ISSUE THREAD

**Issue by aniqueta** [ChuckPa/PlexDBRepair#136]
Thanks for a super useful and user friendly script. 

On macOS, the script looks for the cache at `~/Library/Application Support/Plex Media Server/Cache`. 

However, by default, Plex stores the cache at `~/Library/Caches/PlexMediaServer`.

Could this be updated in the appropriate places in the script? Thank you.

**Comment by ChuckPa** [comment]
ABSOLUTELY ,  I'll update that ASAP

**Comment by ChuckPa** [comment]
Followup.

"Plex Media Server"
-or-
"PlexMediaServer"

(important)

**Comment by ChuckPa** [comment]
It will look like:

> 
> CacheDir="$AppSuppDir/Plex Media Server/Cache"
> TransCacheDir="$CacheDir/PhotoTranscoder"

which is based on:

```
    PLEX_SQLITE="/Applications/Plex Media Server.app/Contents/MacOS/Plex SQLite"
    AppSuppDir="$HOME/Library/Application Support"
    DBDIR="$AppSuppDir/Plex Media Server/Plug-in Support/Databases"
    CacheDir="$HOME/Library/Caches/Plex Media Server"
```

**Comment by aniqueta** [comment]
> Followup.
> 
> "Plex Media Server" -or- "PlexMediaServer"
> 
> (important)

On PMS 1.40.0.7998 and macOS 14.3.1 it is without spaces.

**Comment by ChuckPa** [comment]
Please try this.

https://github.com/ChuckPa/PlexDBRepair/blob/chuckpa/macos-cache-dir/DBRepair.sh

**Comment by aniqueta** [comment]
Hm. I still get this error:

```
Enter command # -or- command name (4 char min) : prune
 
Counting how many files are more than 30 days old.
find: /Users/@@@@@/Library/Caches/Plex Media Server/PhotoTranscoder: No such file or directory
No files found to prune.
```

**Comment by ChuckPa** [comment]
Please do the following for me?

1.   `cd $HOME/Library`
2.   `ls -la`
3.   `ls -la Plex*`

I don't have a Mac to develop on so am counting on you to be my eyes.

I need to see the directory structure

**Comment by aniqueta** [comment]
`zsh: no matches found: Plex*`

The location of the directory the script is looking for `$HOME/Library/Caches/PlexMediaServer/PhotoTranscoder`

Note it's not in `Application Support` but instead in `Caches` and there are indeed no spaces.

**Comment by ChuckPa** [comment]
That is so bizarre.  I need to go into the PMS source and find out why MacOS changed.

I will publish as soon as I've confirmed this is the same for all MacOS versions

**Comment by aniqueta** [comment]
I suppose `ls -la Plex*` didn't go recursively through directories on macOS.

No, there is also a directory at `$HOME/Library/Application Support/Plex Media Server` (with spaces here 🤷‍♂️) that has the following sub-directories:

```
Codecs          Diagnostics     Media           Plug-in Support Scanners        Thumbnails      update-log.txt
Crash Reports   Drivers         Metadata        Plug-ins        Setup Plex.html Updates
```

And for reference, here's what's at `$HOME/Library/Caches/PlexMediaServer/PhotoTranscoder`

```
CL-ICDs                       CloudUsersSubscriptionsV2.dat PhotoTranscoder               autotag_wordlist.json
CloudAccessV2.dat             CloudUsersV2.dat              Privacy.dat                   cert-v2.p12
CloudAccountV2.dat            Flags.dat                     Transcode
CloudUsersServices.dat        OCSP                          UpdateChannels.dat
```

**Comment by ChuckPa** [comment]
Thank you.   That's what I needed to see.

**Comment by ChuckPa** [comment]
Test drive please.

https://github.com/ChuckPa/PlexDBRepair/blob/chuckpa/macos-cache-dir/DBRepair.sh

**Comment by ChuckPa** [comment]
V1.05.01 is released.   The pull request closes the issue.  Let me know if still have problems.

**Comment by aniqueta** [comment]
Thanks @ChuckPa. It worked (as expected, given forum thread).
