### ISSUE TITLE
Error: Unknown Host - unRAID Linuxserver Docker

### ISSUE THREAD

**Issue by rh535** [ChuckPa/PlexDBRepair#137]
I'm running into an error after I type in ./DBRepair.sh.

I have Plex in a docker container from Linuxserver.

Would you have any thoughts on how to fix this error? I believe it should be supported. Thanks for all your work!

![Screenshot 2024-03-07 165031](https://github.com/ChuckPa/PlexDBRepair/assets/25569936/e301fc46-ce95-43e1-867d-7b1a95550f96)

**Comment by ChuckPa** [comment]
@rh535 

Unraid is supported.    Some images are not.

Whose image are you using to create the container

**Comment by ChuckPa** [comment]
LSIO is supported.

Go recheck and make certain you are INSIDE the container when you invoke my tool

What you showed me looked like you ran it from the Unraid web browser "terminal" window (?)

**Comment by ChuckPa** [comment]
You have an issue within the container

I would try a wildcard    `cd  PlexDB*`   and see if it picks up on that.

If it still doesn't then download the tar.gz again... -OR- just grab the PlexDBRepair.sh directly
