### ISSUE TITLE
Issue Detecting Plex installation latest Hotio Docker

### ISSUE THREAD

**Issue by Healzangels** [ChuckPa/PlexDBRepair#140]
Greetings!

Came across an issue with the DBRepair script while trying to run on the latest version of the hotio plex docker container. 
The issue begins following release-c98b17e which I believe from some digging is when the container went from being built on ubuntu to alpine. 
![DBRepairError](https://github.com/ChuckPa/PlexDBRepair/assets/47136415/8345760b-73c6-4744-8145-e7b6170f3dd2)

Assume that's where the issue is stemming as some of the paths change/what the script checks again are no longer the same path.
Believe the new path is: `/app/bin/usr/lib/plexmediaserver/Resources/`

Happy to provide any additional logs/configs/test anything. 

Thanks!

**Comment by ChuckPa** [comment]
If you go into the script,   find the test for HOTIO.

You can edit where it looks and then edit the values set in the variables as confirmation everything works.

**Comment by ChuckPa** [comment]
If you look at DBRepair.sh  directly and download it, you'll find it contains a user-submitted change which should address what you're seeing.

Care to give that a try as well ?

**Comment by Healzangels** [comment]
Awesome, thanks so much for the suggestions! I’ll give them a whirl this evening but sounds like one of the two will get me going. Thanks again and have a great week!

**Comment by minermartijn** [comment]
This is still an issue for me, and not sure how to fix it with the above mentioned method.

**Comment by Healzangels** [comment]
https://github.com/ChuckPa/PlexDBRepair/commit/4d880bf788a70510d70823f673b6b4b09771083e

**Comment by minermartijn** [comment]
Thank you, this did work for me now.

**Comment by ChuckPa** [comment]
Release v1.05.02 contains this fix;  released today
