### ISSUE TITLE
Error 1 From Plex SQLite while importing

### ISSUE THREAD

**Issue by Guegs** [ChuckPa/PlexDBRepair#141]
Hi there,

I think my Plex DB is pretty mangled, and I get the following errors after running command 5 'repair'
https://pastebin.com/dY6We6DK

My Plex library is fairly large, around 1500 movies and 15,000 episodes. I am running on Unraid with Plex in a Docker. 

Any ideas on what I can try? I am fairly new/inexperienced with this sort of stuff.

**Comment by Zodiaksl** [comment]
Hello,

I am getting the same thing. I received a notification of a newer version of Plex. I stopped my Plex server, downloaded the new package, updated to the new version of Plex and after starting Plex again, I have an XML error menu and plex no longer starts.

I looked everywhere. I tried the Plex SQLite method, which didn't work. Then I found your github and followed the instructions and did an Automatic repair.

I have a QNAP server and running Plex as an app, not in a container.

Now after following the steps for Automatic repair, I try doing Step 7 - Start - Start PMS and it returns "Could not start PMS. Error Code: 1"

I also have a large library

Please help

[DBRepair.log](https://github.com/ChuckPa/PlexDBRepair/files/14808664/DBRepair.log)

**Comment by ChuckPa** [comment]
I request you both come to the Plex forum,  with your most recent logs and the DBRepair log file,   posting in a new thread where you ping me.

Be advised,  upgrading to anything 1.40.0 is a huge database schema change internally by PMS
It if gets interrupted and grossly corrupted,  the only choice will be to use a backup and start again

**Comment by ChuckPa** [comment]
@Guegs 

Unique Constraint error happens when you import from one DB into another and there are conflicts.

I specifically added the option to IGNORE constraint errors for this reason when importing watch history

**Comment by Guegs** [comment]
Ahh, OK. I did read about the IGNORE flag but didn't think it would apply. I'll try that and see if it helps. I'll make a post in the Plex forums and link it here either tomorrow or the day after and mark this as 'closed' at that time.

**Comment by ChuckPa** [comment]
In the menu, it specifically states:

>  42 - 'ignore'    - Ignore duplicate/constraint errors.

In the documentation:

> gnore / Honor
>Toggle the state (ON/OFF) of the IGNORE flag. When ON, Duplicates and UNIQUE constraint errors will be ignored. Caution is advised as other errors will be ignored during initial processing.

>In ALL cases, DBRepair will never allow a bad database to be created.
