### ISSUE TITLE
Binhex , unable to stop from command line

### ISSUE THREAD

**Issue by McTavish01** [ChuckPa/PlexDBRepair#150]
1 - 'stop'      - (Not available. Stop manually.)
![Screenshot 2024-05-06 163913](https://github.com/ChuckPa/PlexDBRepair/assets/169112606/6a026cc3-07cf-4d55-b210-03b74c378521)

**Comment by ChuckPa** [comment]
Did binhex  change the control mechanism  ?

I did not make any changes to the binhex container detection.

Have the Image author contact me please

**Comment by convexshiba** [comment]
Hi could you elaborate how to use the code snippet you shared?

**Comment by ChuckPa** [comment]
I will see if I can make that work reliably for everyone.
