### ISSUE TITLE
Question regarding watch history

### ISSUE THREAD

**Issue by jl94x4** [ChuckPa/PlexDBRepair#155]
I am currently creating a new database and would like to keep old watch data, but one question I have regarding this is, does this also import continue watching data? For example, if I am watching X Show on my old server and I got up to S03E04, with S0305 on continue watching and then I import watch data, does this get reflected, or is it just literal watch data only?

Thanks!

**Comment by ChuckPa** [comment]
What you import is a simple   YES/NO flag.   "Have I watched it".

Plex changed (expanded) the information for all this.   Continue Watching is the other part of the information you want which is in the other database (and I can't get to it)

The best solution for your request is this:

![Screenshot from 2024-05-17 12-12-47](https://github.com/ChuckPa/PlexDBRepair/assets/17990272/d1c5a4ca-9732-4477-a2c8-83ea84b85c73)

This will upload all the viewstate, continue watching, and ratings info.
When you create the new db,  with that enabled,  it will all be reloaded (downloaded from the plex.tv server)

**Comment by jl94x4** [comment]
Nice I managed to get this working really well!
