### ISSUE TITLE
Plex DB Cache

### ISSUE THREAD

**Issue by Samekas123** [ChuckPa/PlexDBRepair#156]
What is the recomended cache for PLEX? The default is 40MB,  53K Total movies and 627K total episodes is 40MB still enough?

**Comment by ChuckPa** [comment]
What do your logs show you?
Are you seeing "SLOW QUERY"?
If not, then leave it alone.

We've tested 40MB because that will handle 40,000 records in a single query (search) result as one buffer.
(SQLite will allocate more memory as needed for the transaction then return to the cache size)

**Comment by ChuckPa** [comment]
No reply received.   Presume issue is resolved.   Closing as completed.
