### ISSUE TITLE
ERROR: Cannot write to Databases directory. Insufficient privilege.

### ISSUE THREAD

**Issue by Paradoxum** [ChuckPa/PlexDBRepair#159]
![image](https://github.com/ChuckPa/PlexDBRepair/assets/6451395/d81981ee-a349-4561-a9d8-8ac11314fce1)

I tried making the container priviliged and also making all of plex r/w but no cigar.
Running on Unraid.

**Comment by ChuckPa** [comment]
Most common causes of this:

1.  Not matching the UID/GID correctly
2. We have found 'docker-mods' causes false reporting of not being able to write.

**Comment by Paradoxum** [comment]
I ended up setting up an ubuntu VM and using that and it ran fine, I had to disable that error detection though, what  is that exactly?

**Comment by ChuckPa** [comment]
If you mean "ignore errors"  then it will continue without stopping  unless the DB is completely unusable.

If you were in a VM with uid/gid matching -or- root passthrough correct to the mapped directory,  it should have worked.

I wish I could figure out why some docker images don't behave nicely
