### ISSUE TITLE
Library can only read by users on web and windows apps

### ISSUE THREAD

**Issue by Morlock19** [ChuckPa/PlexDBRepair#163]
I have a couple issues that i'm hoping you can help me with. i'm running PMS on windows, and i've been trying to upgrade to the latest version, but when i do it says that the database is corrupted and crashes. many people have suggested that i should use your tool, and i have a few times with no good result. 

the other issue is that even when i'm on the old version that still works, anyone that isn't on the web or the windows app (which i'm assuming is the web app in a wrapper?) can't access the library. they can see what videos are there, they can search for shows and movies, they can see everything on the recommended page, but if they try to look at the library directly or collections it says that the server has no information.

has anyone seen this happen? ive put a lot of custom work into my server for years, i don't think i really can rebuild from scratch.

below is the log from when i tried running the most recent version of PMS:

Jun 08, 2024 13:43:02.635 [13888] INFO - Plex Media Server v1.40.2.8395-c67dce28e - Microsoft PC x64-x64 - build: windows-x86_64 windows - GMT -04:00
Jun 08, 2024 13:43:02.635 [13888] INFO - Windows version: 10.0 (Build 19045), language en-US
Jun 08, 2024 13:43:02.635 [13888] INFO - 12 2904 MHz processor(s): Architecture=9, Level=6, Revision=42243 Processor Identifier=Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
Jun 08, 2024 13:43:02.635 [13888] INFO - Compiler is - MSVC 1929
Jun 08, 2024 13:43:02.635 [13888] DEBUG - "C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe"
Jun 08, 2024 13:43:02.639 [12044] DEBUG - Plex for Windows Store application is not installed
Jun 08, 2024 13:43:02.640 [12044] DEBUG - BPQ: [Idle] -> [Starting]
Jun 08, 2024 13:43:02.642 [12044] DEBUG - FeatureManager: Using cached data for features list
Jun 08, 2024 13:43:02.868 [12044] DEBUG - [CERT] Subject name is /CN=*.55bde36f87cd4e5897545a6f66a00a39.plex.direct
Jun 08, 2024 13:43:02.868 [12044] DEBUG - [CERT] Installed certificate with fingerprint 4d:2f:8f:ad:7f:9f:49:11:3b:61:2e:98:e0:7f:60:5f:43:82:cc:c5.
Jun 08, 2024 13:43:02.868 [12044] DEBUG - [CERT/OCSP] Stapling requests will be made to 'http://r3.o.lencr.org/'.
Jun 08, 2024 13:43:02.868 [12044] INFO - [CERT/OCSP] Successfully retrieved response from cache.
Jun 08, 2024 13:43:02.868 [12044] DEBUG - HttpServer: Listening on IPv6 as well as IPv4.
Jun 08, 2024 13:43:02.869 [12044] DEBUG - HttpServer: Listening on port 32400.
Jun 08, 2024 13:43:02.869 [12044] DEBUG - HttpServer: Listening on port 32401.
Jun 08, 2024 13:43:02.869 [12044] DEBUG - Running server...
Jun 08, 2024 13:43:02.869 [12044] DEBUG - Opening 20 database sessions to library (com.plexapp.plugins.library), SQLite 3.39.4, threadsafe=1
Jun 08, 2024 13:43:02.869 [12440] DEBUG - HttpServer: Set up a thread pool with 2 threads.
Jun 08, 2024 13:43:02.884 [12044] INFO - SQLITE3:0x7ff7cedc7500, 283, recovered 6 frames from WAL file C:\Users\morlo\AppData\Local\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.library.db-wal
Jun 08, 2024 13:43:02.913 [12044] INFO - Running migrations. (EPG 0)
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 0.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 1.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 2.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 3.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 4.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 5.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 6.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 7.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 8.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 9.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 10.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 11.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 12.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 13.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 14.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 15.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 16.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 17.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 18.
Jun 08, 2024 13:43:02.926 [12044] DEBUG - Captured session 19.
Jun 08, 2024 13:43:02.929 [12044] INFO - Running forward migration 202309200901.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 0.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 1.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 2.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 3.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 4.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 5.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 6.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 7.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 8.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 9.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 10.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 11.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 12.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 13.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 14.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 15.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 16.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 17.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 18.
Jun 08, 2024 13:43:02.929 [12044] DEBUG - Captured session 19.
Jun 08, 2024 13:43:03.026 [12044] ERROR - Exception inside transaction (inside=1) (D:\gha\plex-media-server\plex-media-server\Library\DatabaseMigrations.cpp:293): Null value not allowed for this type
Jun 08, 2024 13:43:03.027 [12044] ERROR - Exception thrown during migrations, aborting: Null value not allowed for this type
Jun 08, 2024 13:43:03.063 [12044] DEBUG - ChangestampAllocator: initialized to 13947715
Jun 08, 2024 13:43:03.067 [12044] DEBUG - Opening 2 database sessions to library (com.plexapp.plugins.library.blobs), SQLite 3.39.4, threadsafe=1
Jun 08, 2024 13:43:03.076 [12044] INFO - Running migrations. (EPG 0)
Jun 08, 2024 13:43:03.076 [12044] DEBUG - Captured session 0.
Jun 08, 2024 13:43:03.076 [12044] DEBUG - Captured session 1.
Jun 08, 2024 13:43:03.082 [7720] DEBUG - Codecs: Downloading current version of aac encoder
Jun 08, 2024 13:43:03.082 [7720] INFO - CodecManager: obtaining encoder 'aac'
Jun 08, 2024 13:43:03.082 [7720] DEBUG - [HCl#1] HTTP requesting GET https://plex.tv/api/codecs/aac_encoder?build=windows-x86_64-standard&deviceId=99746e13-b7bd-4abb-a8b2-14cd03edad7e&oldestPreviousVersion=1%2E24%2E5%2E5173-8dcc73a59&version=ad47460-4673
Jun 08, 2024 13:43:03.129 [7720] DEBUG - Grabber: Cleaning up orphaned grabs.
Jun 08, 2024 13:43:03.130 [12044] DEBUG - Media Provider: Registering provider com.plexapp.plugins.library
Jun 08, 2024 13:43:03.130 [12044] DEBUG - Auth: Refreshing tokens inside the token-based authentication filter.
Jun 08, 2024 13:43:03.130 [12044] DEBUG - MyPlex: mapping state set to 'Unknown'.
Jun 08, 2024 13:43:03.131 [7720] DEBUG - Grabber: Cleaned up 0 decrepit directories in 0.0 sec.
Jun 08, 2024 13:43:03.131 [12044] DEBUG - Relay: read 146 cached entries from hosts file
Jun 08, 2024 13:43:03.132 [15736] DEBUG - [MediaProviderManager/HCl#2] HTTP requesting GET https://plex.tv/media/providers?X-Plex-Token=xxxxxxxxxxxxxxxxxxxx
Jun 08, 2024 13:43:03.132 [12044] DEBUG - MyPlex: using cached data for request for https://plex.tv/api/v2/server/access_tokens?auth_token=xxxxxxxxxxxxxxxxxxxx
Jun 08, 2024 13:43:03.133 [12044] DEBUG - MyPlex: updating with 56 access tokens
Jun 08, 2024 13:43:03.133 [12044] ERROR - Error: Unable to set up server: bad cast (class std::bad_cast)

**Comment by ChuckPa** [comment]
This belongs in the Plex forums please.   I can assist you there.

This GitHub is for my tool only.

**Comment by Morlock19** [comment]
sorry about that, when id id someone told me to ask you here... i'll remember this for the future.

here is a link tot he post if you'd like to look at it? https://www.reddit.com/r/PleX/comments/1dg6ewc/users_on_apps_cant_see_library_and_i_cant_upgrade/
