### ISSUE TITLE
Cannot stop PMS. Server reports no content afterwords

### ISSUE THREAD

**Issue by liquid-ion** [ChuckPa/PlexDBRepair#166]
Hello,

Have been running PlexDBRepair on a weekly basis since January. Today I went to check DB again, noticed that DBRepair gives an error that it cannot stop the database.

Docker PMS appears working prior to starting DBRepair. Connection is in green status, content is playing on clients.

DBRepair tries to stop the server and start the status check. It errors after 30seconds saying the server couldn't be stopped. Immediately afterwords I notice the server becomes unreachable/no WebUI from the internal address (the 192.168.X.XXX address).

Restart PMS container, everything is ok again. 

Is there a way to use DBRepair if it can't stop PMS while it runs in the docker container console? 

Thanks

**Comment by ChuckPa** [comment]
1.   Stop the container
2.  Use the manual mode  (examples in the README)  how to specify the paths to Plex SQLite and the databases.

**Comment by liquid-ion** [comment]
Sorry to impose on you like this, I'm getting the following error when I try to execute manually, do you see anything wrong with this? I do not know Linux well so any help appreciated:

I modeled off this example:

root@Jasper:/mnt/user/appdata/PlexMediaServer# /tmp/DBRepair.sh --databases /mnt/user/appdata/PlexMediaServer/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/ --sqlite /var/lib/docker/btrfs/subvolumes/4bb78fb70589d4d2ba56754f4d6bc0edd4cdaa8eab7986943767e09a66cefd19/usr/lib/plexmediaserver/

This is my SQLite location:

/var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/Plex SQLite

The command I'm running:

root@LIBRARY:/mnt/user/appdata/Plex-Media-Server# /mnt/user/appdata/Plex-Media-Server/DBRepair/DBRepair.sh --databases  /mnt/user/appdata/Plex-Media-Server/Library/Application\ Support/Plex\ Media\ Server/Plug-In\ Support/Databases/ --sqlite /var/lib/docker/btrfs/subvo
lumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/

The error:
[2024-06-28 13.28.00] Error: Unknown host. Current supported hosts are: QNAP, Syno, Netgear, Mac, ASUSTOR, WD (OS5), Linux wkstn/svr, SNAP
[2024-06-28 13.28.00]                      Current supported container images:  Plexinc, LinuxServer, HotIO, & BINHEX
[2024-06-28 13.28.00]  
[2024-06-28 13.28.00] Are you trying to run the tool from outside the container environment ?

---

What am I doing wrong?

**Comment by ChuckPa** [comment]
when you specify --sqlite or --databases,  it goes into manual configuration mode.

If those values don't work,  it jumps back to normal dynamic (automatic) configuration mode.

does 
```
ls -la /var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/
```
show you the executables as you expect from `ls -la` on a native host ?

**Comment by ChuckPa** [comment]
Another option for you:

1. get into a running container.
2. there should be the service files in `/`   (Plex docker has it)
3. from there,  `/plex_service.sh -d`   (bring pms down)
4.  now run plex.sh from within the container  (be quick)
5. when done,  restart the container

**Comment by liquid-ion** [comment]
> when you specify --sqlite or --databases, it goes into manual configuration mode.
> 
> If those values don't work, it jumps back to normal dynamic (automatic) configuration mode.
> 
> does
> 
> ```
> ls -la /var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/
> ```
> 
> show you the executables as you expect from `ls -la` on a native host ?

It shows the following output, does this look right?

![image](https://github.com/ChuckPa/PlexDBRepair/assets/6819840/0ca5808c-1d90-4b98-add8-0d8c833549c7)


>Another option for you...

Not sure if I understand your instructions, what does "there should be the service files in / (Plex docker has it)" this mean?

**Comment by ChuckPa** [comment]
In the code,   I support both forms:
1.  the directory containing "Plex SQLite"
-or-
2. the full path to "Plex SQLite"   (you must escape the space or use quotes)

Observe:
```
  # Manual configuration options (running outside of container or unusual hosts)
  if [ "$Opt" = "--sqlite" ]; then

    # Is this the directory where Plex SQLite exists?
    if   [ -d "$2" ] && [ -f "$2/Plex SQLite" ]; then
      PLEX_SQLITE="$2/Plex SQLite"
      ManualConfig=1

    # Or is it the direct path to Plex SQLite
    elif echo "$2" | grep "Plex SQLite" > /dev/null  && [ -f "$2" ] ; then
      PLEX_SQLITE="$2"

    else
      Output "Given 'Plex SQLite' directory/path ('$2') is invalid. Aborting."
      exit 2
    fi
    shift 2
  fi

```



OOOPS on the `plex.sh` .  I did mean `DBRepair.sh`.   :facepalm: 


You can run this from outside the container,  with the container stopped,  if you have the full path in the real filesystem. 

When you run inside the container,  I usually:

1.  Put `DBRepair.sh`  under the `/config` directory
2.  docker exec -it  container_name bash
3. cd /config
4. /plex_service.sh -d
5.  ./DBRepair.sh  auto exit      (which will work inside the container for known images)
6. /plex_service.sh -u

**Comment by ChuckPa** [comment]
DOOH.. I think I just found a bug.

```
    # Or is it the direct path to Plex SQLite
    elif echo "$2" | grep "Plex SQLite" > /dev/null  && [ -f "$2" ] ; then
      PLEX_SQLITE="$2"

    else
```

When you specify the full path,  it doesn't go into manual mode.  
Can you tweak that on your end ?  (use the `ManualConfig=1` above as example.

**Comment by liquid-ion** [comment]
Sorry.. Not sure if I follow you. I'm already using the example of ManualConfig1 am I not? Using 'the directory containing "Plex SQLite"' as you say

1) I ran this command, aka the directory containing Plex SQLite:

`root@LIBRARY:/mnt/user/appdata/Plex-Media-Server# /mnt/user/appdata/Plex-Media-Server/DBRepair/DBRepair.sh --databases /mnt/user/appdata/Plex-Media-Server/Library/Application\ Support/Plex\ Media\ Server/Plug-In\ Support/Databases/ --sqlite /var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/`

I tried ManualConfig2, the full path to Plex SQLite with the space escaped, same error:

`/mnt/user/appdata/Plex-Media-Server/DBRepair/DBRepair.sh --databases /mnt/user/appdata/Plex-Media-Server/Library/Application\ Support/Plex\ Media\ Server/Plug-In\ Support/Databases/ --sqlite /var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/Plex\ SQLite/`

We can see in the above screenshot that Plex SQLite is contained here:

![image](https://github.com/ChuckPa/PlexDBRepair/assets/6819840/a3d19cbc-3b09-4362-b368-321d41ff7df1)

>Yes, when using Manual Config, it ignores anything which is preprogrammed.
and t is dependent on you to tell it where the databases are (the directory) and where Plex SQLite is.

That is exactly what I'm doing, can you point out where I'm making the mistake?

**Comment by ChuckPa** [comment]
From what I can see, you're not making any mistakes with the invocation.

The code is a simple file-existence shell test.  

After it confirms the DB's are there (--databases),   it sets DBDIR 
Supplementally, it calculates and sets AppSuppDir.


if you want to insert a debug statement at line 1699,

```
echo  DBDIR=\'$DBDIR\'
```

and at line 1680,  
```
echo SQLite=\'$PLEX_SQLITE\'
```

This will confirm the arguments are getting in OK.

**Comment by ChuckPa** [comment]
Look VERY carefully at what you typed..

```
Server/Plug-In\ Support/
```

The path is 
```
Server/Plug-in\ Support
```

Lowercase 'i'

**Comment by liquid-ion** [comment]
I fixed that typo but still get the same error:

root@LIBRARY:/mnt/user/appdata/Plex-Media-Server# **/mnt/user/appdata/Plex-Media-Server/DBRepair/DBRepair.sh --databases /mnt/user/appdata/Plex-Media-Server/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/ --sqlite /var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/Plex\ SQLite/**
[2024-07-03 12.53.52] Error: Unknown host. Current supported hosts are: QNAP, Syno, Netgear, Mac, ASUSTOR, WD (OS5), Linux wkstn/svr, SNAP
[2024-07-03 12.53.52]                      Current supported container images:  Plexinc, LinuxServer, HotIO, & BINHEX
[2024-07-03 12.53.52]  
[2024-07-03 12.53.52] Are you trying to run the tool from outside the container environment ?


root@LIBRARY:/mnt/user/appdata/Plex-Media-Server# **/mnt/user/appdata/Plex-Media-Server/DBRepair/DBRepair.sh --databases /mnt/user/appdata/Plex-Media-Server/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/ --sqlite /var/lib/docker/btrfs/subvolumes/b45db925b9ea70d255dacf0485930f64684dec4f1cf4382f10c1c63426d38ed4/usr/lib/plexmediaserver/**
[2024-07-03 12.53.56] Error: Unknown host. Current supported hosts are: QNAP, Syno, Netgear, Mac, ASUSTOR, WD (OS5), Linux wkstn/svr, SNAP
[2024-07-03 12.53.56]                      Current supported container images:  Plexinc, LinuxServer, HotIO, & BINHEX
[2024-07-03 12.53.56]  
[2024-07-03 12.53.56] Are you trying to run the tool from outside the container environment ?

I have absolutely made sure the paths match this time:

![image](https://github.com/ChuckPa/PlexDBRepair/assets/6819840/bcdcb819-611e-4710-9703-e60043ac9e91)

Still not sure what I'm doing wrong in this latest iteration with the typo corrected

**Comment by ChuckPa** [comment]
I don't know what's happening with the BTRFS subvolumes  but I have no trouble.

This is what you should see:

```
[chuck@lizum PlexDBRepair.2030]$ ./DBRepair.sh --sqlite /usr/lib/plexmediaserver --databases "/usb/plex/Plex Media Server/Plug-in Support/Databases"
ERROR:  Tool running as username 'chuck'.  'User Defined' requires 'root' user privilege.
        (e.g 'sudo -su root' or 'sudo bash')
        Exiting.
[chuck@lizum PlexDBRepair.2031]$ sudo !!
sudo ./DBRepair.sh --sqlite /usr/lib/plexmediaserver --databases "/usb/plex/Plex Media Server/Plug-in Support/Databases"
 
 
 
      Plex Media Server Database Repair Utility (User Defined)
                       Version v1.07.01
 
      PlexSQLite = '/usr/lib/plexmediaserver/Plex SQLite'
      Databases  = '/usb/plex/Plex Media Server/Plug-in Support/Databases'

Select

  1 - 'stop'      - (Not available. Stop manually.)
  2 - 'automatic' - Check, Repair/Optimize, and Reindex Database in one step.
  3 - 'check'     - Perform integrity check of database.
  4 - 'vacuum'    - Remove empty space from database without optimizing.
  5 - 'repair'    - Repair/Optimize databases.
  6 - 'reindex'   - Rebuild database indexes.
  7 - 'start'     - (Not available. Start manually)

  8 - 'import'    - Import watch history from another database independent of Plex. (risky).
  9 - 'replace'   - Replace current databases with newest usable backup copy (interactive).
 10 - 'show'      - Show logfile.
 11 - 'status'    - Report status of PMS (run-state and databases).
 12 - 'undo'      - Undo last successful command.

 21 - 'prune'     - Prune (remove) old image files (jpeg,jpg,png) from PhotoTranscoder cache.
 42 - 'ignore'    - Ignore duplicate/constraint errors.

 88 - 'update'    - Check for updates.
 99 - 'quit'      - Quit immediately.  Keep all temporary files.
      'exit'      - Exit with cleanup options.

Enter command # -or- command name (4 char min) :
```

**Comment by liquid-ion** [comment]
Thank you for your help and time. This works now - I didn't realize there was a newer version - upgraded from 1.05 and everything works now

**Comment by ChuckPa** [comment]
Which version of DBRepair are you using  and which version of the Plex container are you using?

**Comment by ChuckPa** [comment]
No reply.  Closing.
