### ISSUE TITLE
Feature Request: Clear Watch States

### ISSUE THREAD

**Issue by brettpetch** [ChuckPa/PlexDBRepair#169]
As an additional function to pair with watch state importing, watch state clearing could also be beneficial if someone wanted to give the db a good cleaning. Bash below. Can follow-up later with a PR.

```bash
"Plex SQLite" com.plexapp.plugins.library.db "DELETE FROM statistics_resources"
"Plex SQLite" com.plexapp.plugins.library.db "DELETE FROM statistics_media"
"Plex SQLite" com.plexapp.plugins.library.db "DELETE FROM statistics_bandwidth"
"Plex SQLite" com.plexapp.plugins.library.db "DELETE FROM metadata_item_views"
"Plex SQLite" com.plexapp.plugins.library.db "DELETE FROM metadata_item_accounts"
"Plex SQLite" com.plexapp.plugins.library.db "DELETE FROM accounts"
```

**Comment by ChuckPa** [comment]
why not delete the DB and start over ?

Also, this won't address what's in the cloud (Plex.tv)

**Comment by ChuckPa** [comment]
Will consider how to implement less destructively.
Closing this issue.
