### ISSUE TITLE
Not running on Windows 11

### ISSUE THREAD

**Issue by montizzl3** [ChuckPa/PlexDBRepair#170]
I have read the instructions to run DBRepair-Windows.ps1 but must have missed something.  I downloaded the .ps1 script, set the execution policy to allow it, and ran it but I just get:

PS C:\users\monte\Downloads> .\DBRepair-Windows.ps1
At C:\users\monte\Downloads\DBRepair-Windows.ps1:40 char:60
+ ... script type="application/json" id="client-env">{"locale":"en","featur ...
+                                                             ~~~~~
Unexpected token ':"en"' in expression or statement.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:40 char:65
+ ... cript type="application/json" id="client-env">{"locale":"en","feature ...
+                                                                 ~
Missing argument in parameter list.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:40 char:670
+ ... tions","custom_inp","remove_child_patch","kb_source_repos"]}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:256 char:84
+ ... tion/json" data-target="react-partial.embeddedData">{"props":{"docsUr ...
+                                                                 ~
Unexpected token ':' in expression or statement.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:256 char:95
+ ... ":{"docsUrl":"https://docs.github.com/get-started/accessibility/keybo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token ':"https://docs.github.com/get-started/accessibility/keyboard-shortcuts"' in expression or statement.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:256 char:168
+ ... s.github.com/get-started/accessibility/keyboard-shortcuts"}}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:289 char:205
+ ... ink Button--medium Button d-lg-none color-fg-inherit p-1">  <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:323 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:538 char:13
+       CI/CD &amp; Automation
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\users\monte\Downloads\DBRepair-Windows.ps1:669 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

Any help with what I am missing?

**Comment by danrahn** [comment]
It looks like you saved the entire Github web page, not just the script itself. To make sure you're saving/downloading the right script, you could do any of the following:

* Download the full source code as a zip file, and extract the Windows script: https://github.com/ChuckPa/PlexDBRepair/archive/refs/heads/master.zip
* Download the source zip from the latest release: https://github.com/ChuckPa/PlexDBRepair/releases
* Download just the PowerShell script: https://raw.githubusercontent.com/ChuckPa/PlexDBRepair/master/Windows/DBRepair-Windows.ps1

**Comment by montizzl3** [comment]
Wow, I don't know how the .ps1 file I downloaded was different but you are correct.  I downloaded the whole zip file and ran the .ps1 in there and it is now running.  Thanks for giving me a knock in the head!
