### ISSUE TITLE
Runtime Error when trying to repair broken main DB

### ISSUE THREAD

**Issue by andi-gashi** [ChuckPa/PlexDBRepair#171]
I currently have a stalled Plex Database where nothing new is getting recognised. This is the error message I get when I run the tool:

Runtime error near line 1384463: UNIQUE constraint failed: fts4_metadata_titles_icu_segdir.level, fts4_metadata_titles_icu_segdir.idx (19)
Runtime error near line 1384464: UNIQUE constraint failed: fts4_metadata_titles_icu_segdir.level, fts4_metadata_titles_icu_segdir.idx (19)
Runtime error near line 1384465: UNIQUE constraint failed: fts4_metadata_titles_icu_segdir.level, fts4_metadata_titles_icu_segdir.idx (19)
Error 1 from Plex SQLite while importing from './dbtmp/library.plexapp.sql-2024-08-11_20.22.21'

**Comment by ChuckPa** [comment]
What task are you trying to perform?

Which version of PMS ?  

What you're showing makes no sense.   It's as if your DB is importing itself twice  
> Error 1 from Plex SQLite while importing from './dbtmp/library.plexapp.sql-2024-08-11_20.22.21'

Did you suffer a major PMS crash?

**Comment by hot22shot** [comment]
Hello,

I had the same issue as original poster, the error messages was the same and my library stopped being updated with new item.
It was solved by :

- Stopping PMS
- Ignoring the constraints errors.
- Automatic repair
- Start PMS

It took just a few minutes of downtime.
According to the script there is no error anymore.

Thanks for your script ! It definitly saved me from zeroed my db and start from scratch.
