### ISSUE TITLE
Plex DBRepair

### ISSUE THREAD

**Issue by wdpaynter** [ChuckPa/PlexDBRepair#175]
My Plex DB keeps becoming corrupted. I am not certain what is causing it. I have attempted to repair it using [ChuckPa ](https://github.com/ChuckPa)/ [PlexDBRepair](https://github.com/ChuckPa/PlexDBRepair). Every time I try it fails with runtime errors. This is the output within the terminal:

Exporting current databases using timestamp: 2024-11-07_14.20.43

Exporting Main DB

Exporting Blobs DB

Successfully exported the main and blobs databases.

Start importing into new databases.

Importing Main DB.

Runtime error near line 7208039: UNIQUE constraint failed: fts4_metadata_titles_icu_docsize.docid (19)

Runtime error near line 7208040: UNIQUE constraint failed: fts4_metadata_titles_icu_docsize.docid (19)

Runtime error near line 7208041: UNIQUE constraint failed: fts4_metadata_titles_icu_docsize.docid (19)

Error 1 from Plex SQLite while importing from './dbtmp/library.plexapp.sql-2024-11-07_14.20.43'

Cannot continue.

I've tried running "automatic" and "repair" and both fail during repair. Any help or insight would be appreciated.

Thanks

**Comment by wdpaynter** [comment]
Here is my log too. Any help is appreciated. Thx
[DBRepair.log](https://github.com/user-attachments/files/17668714/DBRepair.log)

**Comment by ChuckPa** [comment]
A unique constraint error means you have a record in the database with an ID number that's already been used.

This is a genuine error in your DB.

Use the `IGNORE` command to tell it to ignore these constraint errors
Then use AUTO to rebuild the DB.

You will see the constraint errors when you run again but they will be IGNOREd  ;)

When it's done,  turn HONOR mode back on.

**Comment by wdpaynter** [comment]
Thank you. I have since rolled back to a backup DB that Plex had created about a month ago. I had been trying to use a version I had made a few days ago (manually) and it was not working (as described). I also switched from linuxserver container to the official Plex container, as suggested on Reddit. If Plex notifies me that this one has been corrupted, I will do as instructed. No DB corruption notification overnight last night from Plex...

If I run a "check" on my current DB using your utility, it shows "ok". Would the log still show any of what it was showing above if it is "ok"?

I appreciate your help!

**Comment by ChuckPa** [comment]
The check would show as OK because the SQL structure of the DB is indeed ok.

The constraint error is only occurring when using the data in the records of the database.
Unfortunately,  checking record contents is beyond what I can do (I'd have to know the schema of every PMS version in existance).
