### ISSUE TITLE
Transfer full history of media views when transferring viewstate

### ISSUE THREAD

**Issue by ChuckPa** [ChuckPa/PlexDBRepair#19]
Instead of transferring only the yes/no of viewstate (watched history),
Also transfer the associated history of which users watched which items.

**Comment by ChuckPa** [comment]
@2bits 

I've been requested to add full view history to viewstate transfer.

Would you be able to test this.
Also, please carefully review the logic and naming changes I made since the previous version.
The initial code was cumbersome.   I needed to rework it and make it right.

**Comment by 2bits** [comment]
Okay I'll take a look.

**Comment by 2bits** [comment]
The logic is okay. I'll do some testing of the commit after lunch.

**Comment by ChuckPa** [comment]
I've got the mac mini up and running.   it should help a great deal with testing here

**Comment by 2bits** [comment]
I finished testing your commit on my Mac. It was a success.
Each managed user had their unique watch history imported.
I added a single note to the commit showing how to fix some spacing.
