### ISSUE TITLE
Support Mac

### ISSUE THREAD

**Issue by 2bits** [ChuckPa/PlexDBRepair#2]
The DBRepair script can support Apple Mac.

Closes: #9 

With a couple of allowances for `pidof` and `stat` I have a working fork.
Testing was done on a Mac Studio and a QNAP, the first few options so far.
Okay, thanks for making it 🍺

**Comment by ChuckPa** [comment]
I am perfectly OK with making allowances 

examples:
1.  A variable or alias
   `$PIDOF 'Plex Media Server'`
-or-
2.  A function within the shell script itself


 `stat` is weird.  QNAP does it one way while others do it other ways.   We might want to generalize it to a function and then hide the details in there.


Thoughs?

**Comment by 2bits** [comment]
I thought it was more in fashion to remove some of the hardcoded things, but more or less just wanted to make as little changes and conditional logic later in your script. $PIDOF was easiest.

As far as `stat` goes, I only noticed all your other supported hosts used `stat -c` and also `%s` so again went the easy route.  

I tried functions last night making a `Plex Media Scanner` script and hassling with /dev/tty output.  I got it working but that was a day of effort where a $STAT seems faster for me.  I'm happy to go with whatever convention you like.

**Comment by 2bits** [comment]
Congratulations on merging the Import Viewstate feature.
Are you going to make a 0.3.4 release?

**Comment by ChuckPa** [comment]
I've updated the documentation.

I had a little trouble with the merge (I tried to edit commit messages and clicked the wrong button afterwards).

It all looks good.  

If you're happy,  I think we can call this 0.4.0 ?  :smile:

**Comment by 2bits** [comment]
gtg here
