### ISSUE TITLE
[Feature Requests] Timestamps

### ISSUE THREAD

**Issue by deathbybandaid** [ChuckPa/PlexDBRepair#25]
Very simple request, add in some timestamps for task start/end and calculate the total runtime of the task and output at the end.

**Comment by ChuckPa** [comment]
When you examine the logfile,  you see the time stamps I use.

These guarantee uniqueness of each step's temp files  along the way
These also chronicle and coordinate in the log file .

I did this to allow you to revert to a specific intermediate DB step along the way (a manual reversion to cp/mv but the data is still there)

Not understanding why it's important to log how long this takes.
Help me understand please ?
