### ISSUE TITLE
[Feature Request] Database Information Output option

### ISSUE THREAD

**Issue by deathbybandaid** [ChuckPa/PlexDBRepair#26]
It might be useful to add an additional option

`0) Database Information Output`

This option would then output quantities of database entries, database size, and a suggested Plex cache size. There could be other potential information here.

This idea stems from the debug option that Pi-hole has, which outputs some very useful information for troubleshooting.

**Comment by ChuckPa** [comment]
Beyond the scope of what I'm trying to do here with this.

On separate topic of Plex cache size,  I will address this in the Plex forums .
