### ISSUE TITLE
Fix missing echo pipe

### ISSUE THREAD

**Issue by 2bits** [ChuckPa/PlexDBRepair#3]
There's a bug report https://forums.plex.tv/t/suggested-sqlite3-db-optimizations/794749/122
and I made a fix in a new fork of mine but seeing as your online :)

`echo $NewSuppDir |`

is needed before a sed in my testing over on https://github.com/2bits/PlexDBRepair/tree/newsuppdir-add-echo

Thanks!

**Comment by ChuckPa** [comment]
I have added  Review so when I approve,  the merge happens and then everything can close.

If you would also add the PR reference here,  it'll all sync and close together.
