### ISSUE TITLE
The path to "Plex SQLLite" is missing the extension

### ISSUE THREAD

**Issue by robdplatt** [ChuckPa/PlexDBRepair#41]
https://github.com/ChuckPa/PlexDBRepair/blob/a38da9e44eba13c5a8646d39050fb26ef1c94bca/DBRepair-WinDev.bat#L25

Had an issue where it said the file could not be found. I noticed the extension was missing from the path. However, my actual issue was that the plex application data is in C:\Program Files (x86), so I switched to %PROGRAMFILES% to %PROGRAMFILES(x86)% as well.

Checking both paths might be helpful.

**Comment by ChuckPa** [comment]
Nobody else has needed it.    I would suspect you have something else happening   because on windows,  you don't need to add `.exe` to every executable command.
