### ISSUE TITLE
Error: Unable to set up server: sqlite3_statement_backend::loadOne: attempt to write a readonly database (N4soci10soci_errorE)

### ISSUE THREAD

**Issue by Dracon09** [ChuckPa/PlexDBRepair#42]
binhex-plexpass on UnRaid 6.11.5

Ran

  1. Check database
  4. Attempt database repair
  3. Reindex database
  9. Exit

When restarting the docker, the log file was full of this error

"Error: Unable to set up server: sqlite3_statement_backend::loadOne: attempt to write a readonly database (N4soci10soci_errorE)"

Based on google search it lead me to change the permissions on the database using this command.

stop the binhex-plexpass docker conatainer, then from the UnRaid main terminal interface run
"sudo chmod -R 777 /mnt/user/appdata/binhex-plexpass/Plex\ Media\ Server/Plug-in\ Support/"

Once that was done I was able to restart the docker container and access plex as normal.

Looks like when the "DBRepair.sh" script re-builds the database the permissions are changed to "root" and they need to be "nobody"

**Comment by ChuckPa** [comment]
Interesting issue:

Existing code does following:

1.  Get owner when first starting

```
  # 4. - Attempt DB repair
  elif [ $Choice -eq 4 ]; then

    Damaged=0
    Fail=0

    # Verify DBs are here
    if [ ! -e $CPPL.db ]; then
      Output "No main Plex database exists to repair. Exiting."
      WriteLog "Repair  - No main database - FAIL"
      Fail=1
      continue
    fi

    # Check size
    Size=$(stat $STATFMT $STATBYTES $CPPL.db)

    # Exit if not valid
    if [ $Size -lt 300000 ]; then
      Output "Main database is too small/truncated, repair is not possible.  Please try restoring a backup. "
      WriteLog "Repair  - Main databse too small - FAIL"
      Fail=1
      continue
    fi

    # Continue
    Output "Exporting current databases using timestamp: $TimeStamp"
    Fail=0

    # Get the owning UID/GID before we proceed so we can restore
    Owner="$(stat $STATFMT '%u:%g' $CPPL.db)"
```

2.  After writing DBs, if successful,
```
    # If not failed,  move files normally
    if [ $Fail -eq 0 ]; then

      Output "Saving current databases with '-ORIG-$TimeStamp'"
      [ -e $CPPL.db ]       && mv $CPPL.db       "$TMPDIR/$CPPL.db-ORIG-$TimeStamp"
      [ -e $CPPL.blobs.db ] && mv $CPPL.blobs.db "$TMPDIR/$CPPL.blobs.db-ORIG-$TimeStamp"

      Output "Making imported databases active"
      mv $CPPL.db-$TimeStamp       $CPPL.db
      mv $CPPL.blobs.db-$TimeStamp $CPPL.blobs.db

      Output "Import complete. Please check your library settings and contents for completeness."
      Output "Recommend:  Scan Files and Refresh all metadata for each library section."

      # Remove .sql temp files from $TMPDIR
      # rm -f "$TMPDIR"/*.sql-*

      # Ensure WAL and SHM are gone
      [ -e $CPPL.blobs.db-wal ] && rm -f $CPPL.blobs.db-wal
      [ -e $CPPL.blobs.db-shm ] && rm -f $CPPL.blobs.db-shm
      [ -e $CPPL.db-wal ]       && rm -f $CPPL.db-wal
      [ -e $CPPL.db-shm ]       && rm -f $CPPL.db-shm

      # Set ownership on new files
      chown $Owner $CPPL.db $CPPL.blobs.db
      
```

1.  Your `chmod 777` will work but turns off all permissions for the DB.
2.  The solution is to find out why, in this case,
 -   `chown $Owner` was not applied.    (Is there no 'chown' in the container ???)
3.  Put the DBs manually at  
```
   chown  nobody:nobody   `<put_DB_file_names_here>`
   chmod 644  `<put_DB_file_names_here>`

**Comment by Dracon09** [comment]
Looks like the container runs as nobody
![image](https://user-images.githubusercontent.com/65409337/217132438-d2f16f80-daaf-4d82-9317-d2642889f76b.png)
![image](https://user-images.githubusercontent.com/65409337/217132539-107e0b4a-c4f3-4ed6-aa58-d9118ca6c003.png)

**Comment by Dracon09** [comment]
Just to test that chown and chmod were working in the docker container I tested on a backup database

sh-5.1# chown nobody:nobody com.plexapp.plugins.library.db-2023-02-01
sh-5.1# chmod 644 com.plexapp.plugins.library.db-2023-02-01
sh-5.1# stat com.plexapp.plugins.library.db-2023-02-01
  File: com.plexapp.plugins.library.db-2023-02-01
  Size: 855953408       Blocks: 1671784    IO Block: 4096   regular file
Device: 0,51    Inode: 34254921    Links: 1
Access: (0644/-rw-r--r--)  Uid: (   99/  nobody)   Gid: (65534/  nobody)
Access: 2023-02-01 02:01:03.613866478 -0500
Modify: 2023-02-01 02:01:05.393892951 -0500
Change: 2023-02-06 21:36:02.616609177 -0500
 Birth: 2023-02-01 02:01:03.613866478 -0500

**Comment by ChuckPa** [comment]
Please check  the output of  `stat -c '%u:%g' com.plexapp.plugins.library.db`

It should return that owner of the db  file.

**Comment by Dracon09** [comment]
![image](https://user-images.githubusercontent.com/65409337/217683921-66524d04-3157-476d-9da7-4f15529264a6.png)

**Comment by ChuckPa** [comment]
OK.    `stat -c '%u:%g' com.plexapp.library.db`

If you manually 
```
chown nobody:nobody com.plexapp.plugins.library.db
stat -c '%u:%g' com.plexapp.plugins.library.db
```

You should see the same value you get for `id nobody` (or whichever UID:GID it runs as.
