### ISSUE TITLE
Query: Powershell?

### ISSUE THREAD

**Issue by Berserkir-Wolf** [ChuckPa/PlexDBRepair#46]
Rather than batch file, would it make sense to switch across to PS for the windows version? Or possibly python, since python and sqlite play nicely together.

A lot of the PS commands have aliases assigned for the common 'nix ones (like `wget` and `Invoke-WebRequest`).
Just thinking it could help with multi-arch support.

**Comment by ChuckPa** [comment]
I don't know PowerShell.  I'm not a windows user.

This is written in SH for portability.   Not all environments (NAS platforms)  will have python available.

This tool is largely intended to provide the maintenance functions PMS can't because the DB is always open.

**Comment by Berserkir-Wolf** [comment]
Forked - will try have a look through, but can't promise anything.
Potentially could migrate it to PS, or maybe Net Core with a cross-compiler.

**Comment by ChuckPa** [comment]
Please keep me advised.

**Comment by ChuckPa** [comment]
Closing until such time as I hear of other options.
