### ISSUE TITLE
Runtime error near line 11251 after importing Blobs DB

### ISSUE THREAD

**Issue by sam37git** [ChuckPa/PlexDBRepair#48]
Hi, I have a problem with the utilisation of the script, in automatic mode or in repair I have this: 
Exporting current databases using timestamp: 2023-03-15_12.26.29
Exporting Main DB
Exporting Blobs DB
Successfully exported the main and blobs databases.  Proceeding to import into new databases.
Importing Main DB.
Importing Blobs DB.
Runtime error near line 11251: UNIQUE constraint failed: blobs.linked_type, blobs.linked_id, blobs.blob_type (19)
Error 1 from Plex SQLite while importing from './dbtmp/blobs.plexapp.sql-2023-03-15_12.26.29'
Cannot continue.

How to fix this ? 
Thanks

**Comment by ChuckPa** [comment]
This is a  case where Plex did one of two things:

1.  Didn't write a value to a column  (it's null when NULL isn't allowed)
2.  Tried to write a duplicate record (possibly the real corruption)

As long as the tool isn't crashing,  the recommended best action is to Replace the database from a recent PMS backup.

If there are no backups available,  please let me know so I can improve how this is handled and give you a means to recover.

**Comment by sam37git** [comment]
I guess it's a real corruption, with a other backup no problem, thanks !
