### ISSUE TITLE
Test Watchlist import function in preparation for releasing.

### ISSUE THREAD

**Issue by ChuckPa** [ChuckPa/PlexDBRepair#5]
Purpose here is to verify import from one DB to another works as described and handles errors encountered in the process.

Initial testing looks good.
Would now like second set of eyes;   both testing and general comments  before merging into master.

**Comment by ChuckPa** [comment]
@2bits 

Can you give `chuckpa/watchlist` branch some time to test ?

**Comment by 2bits** [comment]
Will do.

**Comment by 2bits** [comment]
Let me know where the best place would be to make notes like the following.

[ba4474e](https://github.com/ChuckPa/PlexDBRepair/commit/ba4474ed0661c74b0a5d35130da467daa0da9734) line 1108 typo

`    if ! CheckDB "$Input" 2>1 >/dev/null; then`

I could do that here or with an inline comment to your commit.

---

In my repo I searched and replaced all 8 of your `echo -n` with `printf` because sh and echo builtin weirdness.

---

I haven't tested this `DBRepair.sh` yet because my QNAP is parked until after new years.
I think I'll do it on my Mac, though, using my support-mac commits. Good practice cherry-picking :)

**Comment by ChuckPa** [comment]
Updated

580ec279865eee4f8b4247a31c160b11b73da698

**Comment by 2bits** [comment]
1. Basically the CheckDB as previously written created a file called `1` because of the code `2>1` which I figure is hard to spot but I found because I had to relearn shell redirection for the scanner.
 - also would be work but not as intended: `command 2>&1 >/dev/null;`
 - the usual correct way `command >/dev/null 2>&1;`
 - also usual  but might be bash only `command &>/dev/null;`
2.  I read two portable solutions were `printf` or forcing use of `/usr/bin/echo` by using the full path to `echo`. I confirmed both solutions worked for me. This is just a workaround for Apple. I found it weird that every host is okay with `echo -n` but not Apple while the man page it talks about vendors are strongly encouraged to be compliant with such a basic command but they aren't.

**Comment by ChuckPa** [comment]
is this a case  where   `2> /dev/null 1>/dev/null` is what I want ?

**Comment by 2bits** [comment]
Yes that would work and be a long form way of redirecting both STDOUT and STDERR to null.
All of these are equivalent from what I can experience.
- `2> /dev/null 1>/dev/null` 
- `2>/dev/null 1>/dev/null` 
- `1>/dev/null 2>/dev/null`
- `>/dev/null 2>/dev/null`
- `>/dev/null 2>&1`

see also: https://catonmat.net/bash-one-liners-explained-part-three
That article is bash focused but still a very good, modern write up.
I'll be testing the branch tonight after my movie.

**Comment by 2bits** [comment]
My test of Import Viewstate failed on MacOS because of leading whitespace.

### The terminal output I saw:
```
Pathname of database containing watch history to import: /Users/2bits/Misc/com.plexapp.plugins.library.db
Exporting Viewstate / Watch history
./DBRepair.sh: line 1118: [: -lt: unary operator expected
Making backup copy of main database
Importing Viewstate data
Checking database following import
Viewstate import successful.


Enter choice: 6
 
Nothing to undo.



Enter choice: 8

==================================================================================
2022-11-08 23.59.32 - ============================================================
2022-11-08 23.59.32 - Session start: Host is Mac
2022-11-08 23.59.52 - Check   - Check com.plexapp.plugins.library.db - PASS
2022-11-08 23.59.52 - Check   - Check com.plexapp.plugins.library.blobs.db - PASS
2022-11-08 23.59.52 - Check   - PASS
2022-11-09 00.01.56 -  Import  - Import: /Users/2bits/Misc/com.plexapp.plugins.library.db - PASS
2022-11-09 00.04.12 - Undo    - Nothing to Undo.
==================================================================================
```

### The reason why it failed:  wc returned leading whitespeace & cut treated each space as a field.
```
2bits $ TMPDIR="/Users/2bits/Library/Application Support/Plex Media Server/Plug-in Support/Databases/dbtmp"
2bits $ TimeStamp="2022-11-09_00:01:17"
2bits $
2bits $ wc -l "$TMPDIR/Viewstate.sql-$TimeStamp"
    5438 /Users/2bits/Library/Application Support/Plex Media Server/Plug-in Support/Databases/dbtmp/Viewstate.sql-2022-11-09_00:01:17
2bits $ wc -l "$TMPDIR/Viewstate.sql-$TimeStamp" | cut -d " " -f 1

2bits $ wc -l "$TMPDIR/Viewstate.sql-$TimeStamp" | cut -d " " -f 5
5438
2bits $
```

Seems like Mac just adds problems, sorry about that.

**Comment by 2bits** [comment]
[ba4474e](https://github.com/ChuckPa/PlexDBRepair/commit/ba4474ed0661c74b0a5d35130da467daa0da9734) propose a change to line 1088

original
```
    # Make certain we got something usable
     if [ $(wc -l "$TMPDIR/Viewstate.sql-$TimeStamp" | cut -d " " -f 1) -lt 1 ]; then
```

proposed fix strips leading whitespace (tabs or spaces)
```
    # Make certain we got something usable
     if [ $(wc -l "$TMPDIR/Viewstate.sql-$TimeStamp" | sed 's/^[ \t]*//' | cut -d " " -f 1) -lt 1 ]; then
```

`^` - from the beginning of the line
`[ \t]` - match either space or tab
`*` - any number of time with anything else till the end of line

**Comment by 2bits** [comment]
just now I realized it said `Viewstate import successful.` then looked and saw that DBRepair perfectly imported the watch states from my QNAP db to an older Mac. Well done. 😃   So I edited my post above to mention the it succeeded. 

couple of small things -
1 - leading whitespace was addressed above.
2 - tangentially relevant is: on MacOS neither `:` nor `/` are reserved, but when I saw the colon in the `TimeStamp` I immediately had alarm bells because I've run into this - 
- On the command line, you can 
```
$ touch some:file:name.txt
$ ls some*
some:file:name.txt
```
- But in Finder, the `:` is gets transposed

![Finder Colon](https://user-images.githubusercontent.com/1025689/200919997-6ee9aec5-c419-4929-9d96-c74d25ad861b.jpg)

I do [like my Unix](https://en.wikipedia.org/wiki/AT%26T_UNIX_PC), but that seemed creative. (my first 3B1 ran my dad's pharmacy on Bourne scripts)
Anyway because it's just a temp file, I guess there's no need for a more agnostic choice than `:` right?

**Comment by ChuckPa** [comment]
1.   I wanted to use `awk` but thought maybe I could start using `cut`.   Back to `awk` it is..
2.   Awk should resolve the mac.   i don't understand how 
`if [         2 -lt 1 ]; then`
might be different than
`if [ 2 -lt 1; then`

Thoughts?

**Comment by ChuckPa** [comment]
commit:   f45227abc482899a619730efc38ce67532ec1b26

using awk negates the issues.   Oh well, so much for trying to be less resource heavy

```
[chuck@lizum ~.2005]$ echo \[$(wc -l xeon-build.txt | awk '{print $1}')\]
[22]
[chuck@lizum ~.2006]$ wc -l xeon-build.txt 
22 xeon-build.txt
[chuck@lizum ~.2007]$
```

**Comment by 2bits** [comment]
awk works here too, thanks.

**Comment by ChuckPa** [comment]
All updates are in at commit:  303cde633d30a57fd069bfa08d3b1e81711572d7

**Comment by ChuckPa** [comment]
When would you like to add the personality info to `HostConfig()` for MacOS  ?

**Comment by 2bits** [comment]
1. You've done a lot with this branch. I'll test it again shortly.
2. Agree on merging your watchlist into master after I test.
3. Yes then I sync my master with yours.
4. The GHI for my branch is → https://github.com/ChuckPa/PlexDBRepair/issues/2 
5. I'll make a PR for my [support-mac](https://github.com/2bits/PlexDBRepair/tree/support-mac) to your repo after you merge watchlist.
6. The GHI will get the PR, and the PR will get the GHI, yes sir.

Q: What's a good way to slightly corrupt the database?
Q: Would you like me to adjust my branch name and/or GHI title?

**Comment by ChuckPa** [comment]
1.   I don't know how to slightly do it.     If you want to mess it up enough to break verification,  hard kill  PMS and prevent the WAL & SHM from being folded in.    There will be dangling records after that which repair will exclude.

2.  If you'd adjust your branch name to match my structure,  it'll work well if others come in on bigger projects.

**Comment by 2bits** [comment]
I apologize for not understanding the naming just yet. Would you give me a few examples of branch names I might use that match your structure?  If all you mean is rename it to `2bits/support-mac` to be similar to your `chuckpa/watchlist` that's no problem. Thanks.

**Comment by ChuckPa** [comment]
The branch naming `2bits/support-mac`  is exactly what I mean.

1.  It identifies the author
2.  Its name gives a strong hint as to what it's for.

That's all..  No hidden magic there.


Re the edits...  CRAP.   i forgot something AGAIN.   I changed all of it.
Let me go find

**Comment by ChuckPa** [comment]
1.  Corrected the timestamp (again).  Fixed the single `echo -n` in my new code.      aa296cf52dc0f203227f8621b9182cee3aac7296

2.  other examples of the naming convention 

![Screenshot from 2022-11-11 14-00-30](https://user-images.githubusercontent.com/17990272/201412000-86cca350-e596-4074-bf37-b2dd6355ecba.png)

**Comment by 2bits** [comment]
Thanks for those. Before you posted I was writing the following.

---

Without knowing it, I was overwriting a bunch of your edits in my local repo.
After a number of hours relearning the basics, it's fine, and I'm testing again.
While I'm not done yet, there's one small issue of portability and your intent

At Line 779 in your last 303cde6 that has all the updates:
```
      # Edit
      sed -i -e 's/ROLLBACK;/COMMIT;/' "$TMPDIR/library.plexapp.sql-$TimeStamp"
      sed -i -e 's/ROLLBACK;/COMMIT;/' "$TMPDIR/blobs.plexapp.sql-$TimeStamp"
```
The in place edit of the `.sql` file, is your intent to make a backup or not?
For safety, my man page on sed strongly suggests to do a backup.  

_propose:_ These all work on Mac, QTS 4.5.4, rPi Ubuntu

```
[~/testd] # sed -i'.bak' -e 's/x/y/' 'file.txt'
[~/testd] # sed -i.backup -e 's/x/y/' 'file.txt'
[~/testd] # sed -i~ -e 's/x/y/' 'file.txt'
[~/testd] # sed -i.tmp.$$ -e 's/x/y/' 'file.txt'
[~/testd] # l
total 20
-rw-r--r-- 1 admin administrators 35 2022-11-11 10:46 file.txt
-rw-r--r-- 1 admin administrators 35 2022-11-11 10:46 file.txt~
-rw-r--r-- 1 admin administrators 35 2022-11-11 10:45 file.txt.backup
-rw-r--r-- 1 admin administrators 35 2022-11-11 10:45 file.txt.bak
-rw-r--r-- 1 admin administrators 35 2022-11-11 10:46 file.txt.tmp.7032
```

What I saw with your code: `sed -i -e` makes a backup file with extension `-e` on a Mac.
I thing the above methods for a backup are portable and harmless but helpful per the man page.

**Comment by 2bits** [comment]
1. Testing complete. It works great, all aspects.
2. I was able to break it not following directions --  I installed PMS to do **Import Viewstate**. I reindexed first contrary to the directions, and during part of the import steps, I saw several errors.
3. At first I thought, if **Import Viewstate** is making backups, why can't I **Undo**? But I realize I don't know enough to be asking. If you wanted it, you'd code it.
4. In the log after successful **Import Viewstate.** - It's missing the section word.

### What I saw
```
2022-11-11 12.15.34 - ============================================================
2022-11-11 12.15.34 - Session start: Host is Mac
2022-11-11 12.16.11 -  - Check com.plexapp.plugins.library.db - PASS
2022-11-11 12.16.11 -  - Check com.plexapp.plugins.library.blobs.db - PASS
2022-11-11 12.16.13 -  Import  - Import: /Users/nibbles/Misc/com.plexapp.plugins.library.db - PASS
```

### What I expected to see
is another `Check` like when I do choice (1) from Main Menu or an `Import` label
```
2022-11-11 04.16.48 - ============================================================
2022-11-11 04.16.48 - Session start: Host is Mac
2022-11-11 04.17.14 - Check   - Check com.plexapp.plugins.library.db - PASS
2022-11-11 04.17.14 - Check   - Check com.plexapp.plugins.library.blobs.db - PASS
2022-11-11 12.16.13 -  Import  - Import: /Users/nibbles/Misc/com.plexapp.plugins.library.db - PASS

or possibly

2022-11-11 04.16.48 - ============================================================
2022-11-11 04.16.48 - Session start: Host is Mac
2022-11-11 04.17.14 - Import   - Check com.plexapp.plugins.library.db - PASS
2022-11-11 04.17.14 - Import   - Check com.plexapp.plugins.library.blobs.db - PASS
2022-11-11 12.16.13 -  Import  - Import: /Users/nibbles/Misc/com.plexapp.plugins.library.db - PASS
``` 

5. Feature suggestion: Is it worth the trouble to enumerate the `Output` like this?
```
Enter choice: 2
 
[ 1/10] Checking the PMS databases
[ 2/10] Check complete.  PMS main database is OK.
[ 3/10] Check complete.  PMS blobs database is OK.
[ 4/10] Backing up databases
[ 5/10] Backup current databases with '-ORIG-2022-11-11_12.33.30'
[ 6/10] Vacuuming main database
[ 7/10] Vacuuming main database successful (Size: 7MB/7MB).
[ 8/10] Vacuuming blobs database
[ 9/10] Vacuuming blobs database successful (Size: 13MB/13MB).
[10/10] Vacuum complete.
```

**Comment by ChuckPa** [comment]
The in-place editing of the SQL file is:
1.  exporting will write ROLLBACK if there were errors during the export -- which  happens when media is damaged.
2.  It's perfectly OK to edit it there (It's the end of the file and actually results in the file being truncated by 2 bytes.

**Comment by ChuckPa** [comment]
```
[ 1/10] Checking the PMS databases
[ 2/10] Check complete.  PMS main database is OK.
[ 3/10] Check complete.  PMS blobs database is OK.
[ 4/10] Backing up databases
[ 5/10] Backup current databases with '-ORIG-2022-11-11_12.33.30'
[ 6/10] Vacuuming main database
[ 7/10] Vacuuming main database successful (Size: 7MB/7MB).
[ 8/10] Vacuuming blobs database
[ 9/10] Vacuuming blobs database successful (Size: 13MB/13MB).
[10/10] Vacuum complete.
```

Interesting idea.  It allows for justification and helps users know if we got to  `[N of N]` steps successfully.

**Comment by ChuckPa** [comment]
Regarding:


1.    Testing complete. It works great, all aspects.
 2.   I was able to break it not following directions -- I installed PMS to do Import Viewstate. I reindexed first contrary to the directions, and during part of the import steps, I saw several errors.
 3.   At first I thought, if Import Viewstate is making backups, why can't I Undo? But I realize I don't know enough to be asking. If you wanted it, you'd code it.
 4.   In the log after successful Import Viewstate. - It's missing the section word.


If I detect an error,  I automatically discard the temp database.   Did that happen?

**Comment by ChuckPa** [comment]
Looks like I didn't catch any errors during import.
I also didn't redirect STDOUT/STDERR to null .

Should I address ?

**Comment by ChuckPa** [comment]
I see where I was not trapping SQL import errors (hard errors).
I do not know if dupes count as errors or not.  This will require testing.

For now,  I've coded that the import must be fully successful (no errors of any kind).

d581f7fa433d4486dcf8ad1d7c599243d0c2889b

**Comment by ChuckPa** [comment]
I didn't handle all the error recovery correctly when Import failed.
I also didn't ignore duplicate attempts to insert watch history  (UNIQUE Constraint errors)

These are corrected.
b645e0f2059d261b09b1d17cfbdebe488d75c1f1

**Comment by 2bits** [comment]
I don't recall the error very well and didn't write everything down when I realized I caused it. I don't think I saw a FAIL in the logs.  When some of the steps silently didn't occur, I realized a  `[1/10]` style enumeration would have been nifty.

From your latest commit it looks like you took care of restoring the backup in case of a failure.  Good catch. It reminds me of why I wanted to know how to corrupt things and test those conditionals. 

I'll try to break your latest with a reindex & import then gather all the debug info in the morning.

**Comment by 2bits** [comment]
I tested b645e0f and noted in the commit where there's a typo.
After fixing it, I'm able to Reindex then Import without breaking anything.
thanks!

**Comment by ChuckPa** [comment]
Thank you.    That was an interesting typo.

I'd finished the typing ,  shellcheck'd it and then committed.

If you grab the latest from the branch,   e30053be35eceaa0b699d23151a444448003414c  (this is the commit to fix it),
you should be able to run the entire thing without issue.

Are we ready to merge after that?

**Comment by 2bits** [comment]
Yes ready to merge now.
