### ISSUE TITLE
Typing `exit` allows temp files deletion, `99` does not.

### ISSUE THREAD

**Issue by SawkeeReemo** [ChuckPa/PlexDBRepair#69]
Just as the subject says, when typing commands at the main menu, it states that you can use the number or the word. But `99 - exit` produces different results when each is used. `99` automatically retains the temp files, while typing `exit` gives you the option to remove them. This is on version 1.0.4.

**Comment by ChuckPa** [comment]
99 is quit and leave logs
exit is quit and keep logs.

This is deliberate.   I will amend the documentation.

**Comment by ChuckPa** [comment]
I have released updated  v1.0.5  which contains the new functionality.

Please let me know your thoughts?
