### ISSUE TITLE
Truenas/Freebsd

### ISSUE THREAD

**Issue by Winky2000** [ChuckPa/PlexDBRepair#77]
Is there anyway to get this to work on Truenas/Freebsd?
Currently running Version:
TrueNAS-13.0-U4
It runs but gives me Error: Unknown host. Current supported hosts are: QNAP, Syno, Netgear, Mac, ASUSTOR, WD (OS5), Linux wkstn/svr
                     Current supported container images:  Plexinc, LinuxServer, HotIO, & BINHEX
Sorry if this is in the wrong place.

**Comment by ChuckPa** [comment]
This is the right place to ask. 


If there's a need,  there's no reason not to add support.



There's some things I'll need to know.

On TrueNAS,  
  -- TrueNAS Core or TrueNAS Scale ?
  --  Are both Docker/LXC containers?   (if so,  whose containers)

If this is a TrueNAS-provided image,   I'll need to know how to uniquely identify it from INSIDE the container.
(A directory listing -- `ls -la /` is usually a good start)

**Comment by Winky2000** [comment]
I'm running it as a native jail plugin
From the root 
drwxr-xr-x    15 plex  plex      20 Jun  4 00:00 Plex Media Server
From the Plex Medial Server folder
drwxr-xr-x   7 plex  plex       7 Jun  3 22:40 Plug-in Support
From Plug-in Support folder 
drwxr-xr-x   2 plex  plex  21 Jun  4 02:12 Databases
From Databases folder
drwxr-xr-x  2 plex  plex          21 Jun  4 02:12 .
drwxr-xr-x  7 plex  plex           7 Jun  3 22:40 ..
-rw-r--r--  1 plex  plex      106496 May 14 22:28 com.plexapp.dlna.db
-rw-r--r--  1 plex  plex       32768 May 15 06:23 com.plexapp.dlna.db-shm
-rw-r--r--  1 plex  plex      362592 May 14 22:28 com.plexapp.dlna.db-wal
-rw-r--r--  1 plex  plex  1483482112 Jun  2 12:15 com.plexapp.plugins.library.blobs.db
-rw-r--r--  1 plex  plex  1454577664 May 26 02:05 com.plexapp.plugins.library.blobs.db-2023-05-26
-rw-r--r--  1 plex  plex  1456094208 May 29 02:04 com.plexapp.plugins.library.blobs.db-2023-05-29
-rw-r--r--  1 plex  plex  1470295040 Jun  1 02:04 com.plexapp.plugins.library.blobs.db-2023-06-01
-rw-r--r--  1 plex  plex  1484268544 Jun  4 02:12 com.plexapp.plugins.library.blobs.db-2023-06-04
-rw-r--r--  1 plex  plex    11501568 Jun  2 00:50 com.plexapp.plugins.library.blobs.db-shm
-rw-r--r--  1 plex  plex  1504671272 Jun  4 09:39 com.plexapp.plugins.library.blobs.db-wal
-rw-r--r--  1 plex  plex   566648832 Jun  4 09:58 com.plexapp.plugins.library.db
-rw-r--r--  1 plex  plex   552743936 May 26 02:03 com.plexapp.plugins.library.db-2023-05-26
-rw-r--r--  1 plex  plex   558524416 May 29 02:02 com.plexapp.plugins.library.db-2023-05-29
-rw-r--r--  1 plex  plex   565109760 Jun  1 02:02 com.plexapp.plugins.library.db-2023-06-01
-rw-r--r--  1 plex  plex   566648832 Jun  4 02:05 com.plexapp.plugins.library.db-2023-06-04
-rw-r--r--  1 plex  plex     4325376 Jun  1 21:38 com.plexapp.plugins.library.db-shm
-rw-r--r--  1 plex  plex   566448224 Jun  4 10:01 com.plexapp.plugins.library.db-wal
-rwxr-xr-x  1 root  plex       52890 Jun  3 22:27 DBRepair.sh
-rwxr-xr-x  1 root  plex     1094462 Apr 11  2022 settings.sql
I put the DBRepair.sh in the Databases folder and tried to run it from there in ssh logged into the jail running Plex
I believe the path from inside the jail is /Plex\ Media\ Server/Plug-in\ Support/Databases
Let me know what else you may need, Happy to help any way I can.

**Comment by ChuckPa** [comment]
I need to see the root  (ls -la /)

I don't care what's down inside (that will always be Plex stuff).
I need to see how to identify the container when the tool is looking for files / directories which are unique to the TrueNAS image

**Comment by Winky2000** [comment]
drwxr-xr-x    21 root  wheel     27 Jun  3 12:38 .
drwxr-xr-x    21 root  wheel     27 Jun  3 12:38 ..
-rw-r--r--     2 root  wheel   1023 Apr  8  2021 .cshrc
-rw-r--r--     2 root  wheel    507 Apr  8  2021 .profile
drwxr-xr-x     2 root  wheel     46 Oct 26  2022 bin
drwxr-xr-x    15 root  wheel     66 Oct 26  2022 boot
-r--r--r--     1 root  wheel   6109 Apr  8  2021 COPYRIGHT
dr-xr-xr-x    15 root  wheel    512 May 23 21:36 dev
drwxr-xr-x    27 root  wheel    108 May 23 21:36 etc
drwxr-xr-x     5 root  wheel     67 Oct 26  2022 lib
drwxr-xr-x     3 root  wheel      5 Apr  8  2021 libexec
drwxr-xr-x     2 root  wheel      2 Apr  8  2021 media
drwxr-xr-x    11 root  wheel     11 May 22  2022 mnt
drwxr-xr-x     2 root  wheel      2 Apr  8  2021 net
drwxr-xr-x     2 plex  plex       2 Apr 10  2022 Plex
drwxr-xr-x    15 plex  plex      20 Jun  4 00:00 Plex Media Server
drwxrwxr-x     2 root  wheel      9 May 31 20:21 PlexDBRepair-1.0.7
-rwxr-xr-x     1 root  wheel   9412 Dec 21 07:51 PMS_Updater.sh
dr-xr-xr-x     2 root  wheel      2 Apr  8  2021 proc
drwxr-xr-x     2 root  wheel    150 Oct 26  2022 rescue
drwxr-x---     2 root  wheel     10 Jun  3 17:15 root
drwxr-xr-x     2 root  wheel    137 Apr 10  2022 sbin
lrwxr-xr-x     1 root  wheel     11 Apr 10  2022 sys -> usr/src/sys
drwxrwxrwt  1010 root  wheel   1537 Jun  4 05:32 tmp
drwxr-xr-x    14 root  wheel     14 Apr 10  2022 usr
-rw-r--r--     1 root  wheel  24819 Jun  3 12:37 v1.0.7.tar.gz
drwxr-xr-x    24 root  wheel     24 May 23 21:36 var

I will try and find SQLite

Jail is like a container similar to docker type but specific to Truenas I believe.

**Comment by Winky2000** [comment]
Plex SQLite location
/usr/local/share/plexmediaserver-plexpass/Plex SQLite

**Comment by Winky2000** [comment]
I installed the Plex Pass version of plugin so the paths would be different for non plex pass. I can install that one and get you info for it also if you would like.

**Comment by Winky2000** [comment]
Fresh clean install folder directory.
drwxr-xr-x  20 root  wheel    24 Jun  4 11:12 .
drwxr-xr-x  20 root  wheel    24 Jun  4 11:12 ..
-rw-r--r--   2 root  wheel  1023 May 12  2022 .cshrc
-rw-r--r--   2 root  wheel   507 May 12  2022 .profile
drwxr-xr-x   2 root  wheel    46 May 12  2022 bin
drwxr-xr-x  14 root  wheel    65 May 12  2022 boot
-r--r--r--   1 root  wheel  6109 May 12  2022 COPYRIGHT
dr-xr-xr-x  15 root  wheel   512 Jun  4 11:33 dev
drwxr-xr-x  28 root  wheel   109 Jun  4 11:33 etc
drwxr-xr-x   5 root  wheel    67 May 12  2022 lib
drwxr-xr-x   3 root  wheel     5 May 12  2022 libexec
drwxr-xr-x   2 root  wheel     2 May 12  2022 media
drwxr-xr-x   2 root  wheel     2 May 12  2022 mnt
drwxr-xr-x   2 root  wheel     2 May 12  2022 net
drwxr-xr-x   2 plex  plex      2 Jun  4 11:12 Plex
drwxr-xr-x  14 plex  plex     17 Jun  4 11:38 Plex Media Server
dr-xr-xr-x   2 root  wheel     2 May 12  2022 proc
drwxr-xr-x   2 root  wheel   150 May 12  2022 rescue
drwxr-x---   2 root  wheel     9 Jun  4 11:23 root
drwxr-xr-x   2 root  wheel   149 May 12  2022 sbin
lrwxr-xr-x   1 root  wheel    11 Jul  5  2022 sys -> usr/src/sys
drwxrwxrwt   8 root  wheel     9 Jun  4 11:40 tmp
drwxr-xr-x  14 root  wheel    14 Jun  4 11:10 usr
drwxr-xr-x  24 root  wheel    24 Jun  4 11:33 var

**Comment by ChuckPa** [comment]
IF they've maintained Plex standard,   /usr/lib/plexmediaserver will be where the executables are

Can you show me the contents of "COPYRIGHT"  ?   (It might contain something unique to TrueNAS)

**Comment by Winky2000** [comment]
The compilation of software known as FreeBSD is distributed under the
following terms:

Copyright (c) 1992-2021 The FreeBSD Project.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

The 4.4BSD and 4.4BSD-Lite software is distributed under the following
terms:

All of the documentation and software included in the 4.4BSD and 4.4BSD-Lite
Releases is copyrighted by The Regents of the University of California.

Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
        The Regents of the University of California.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
This product includes software developed by the University of
California, Berkeley and its contributors.
4. Neither the name of the University nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

The Institute of Electrical and Electronics Engineers and the American
National Standards Committee X3, on Information Processing Systems have
given us permission to reprint portions of their documentation.

In the following statement, the phrase ``this text'' refers to portions
of the system documentation.

Portions of this text are reprinted and reproduced in electronic form in
the second BSD Networking Software Release, from IEEE Std 1003.1-1988, IEEE
Standard Portable Operating System Interface for Computer Environments
(POSIX), copyright C 1988 by the Institute of Electrical and Electronics
Engineers, Inc.  In the event of any discrepancy between these versions
and the original IEEE Standard, the original IEEE Standard is the referee
document.

In the following statement, the phrase ``This material'' refers to portions
of the system documentation.

This material is reproduced with permission from American National
Standards Committee X3, on Information Processing Systems.  Computer and
Business Equipment Manufacturers Association (CBEMA), 311 First St., NW,
Suite 500, Washington, DC 20001-2178.  The developmental work of
Programming Language C was completed by the X3J11 Technical Committee.

The views and conclusions contained in the software and documentation are
those of the authors and should not be interpreted as representing official
policies, either expressed or implied, of the Regents of the University
of California.


NOTE: The copyright of UC Berkeley's Berkeley Software Distribution ("BSD")
source has been updated.  The copyright addendum may be found at
ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change and is
included below.

July 22, 1999

To All Licensees, Distributors of Any Version of BSD:

As you know, certain of the Berkeley Software Distribution ("BSD") source
code files require that further distributions of products containing all or
portions of the software, acknowledge within their advertising materials
that such products contain software developed by UC Berkeley and its
contributors.

Specifically, the provision reads:

"     * 3. All advertising materials mentioning features or use of this software
      *    must display the following acknowledgement:
      *    This product includes software developed by the University of
      *    California, Berkeley and its contributors."

Effective immediately, licensees and distributors are no longer required to
include the acknowledgement within advertising materials.  Accordingly, the
foregoing paragraph of those BSD Unix files containing it is hereby deleted
in its entirety.

William Hoskins
Director, Office of Technology Licensing
University of California, Berkeley

**Comment by Winky2000** [comment]
/usr/local/share/plexmediaserver-plexpass
drwxr-xr-x   4 root  wheel        17 Jun  4 11:11 .
drwxr-xr-x  29 root  wheel        29 Jun  4 12:35 ..
-r-xr-xr-x   1 root  wheel   1459512 May 17 12:07 CrashUploader
drwxr-xr-x   2 root  wheel        51 Jun  4 11:11 lib
-r-xr-xr-x   1 root  wheel    262344 Jun  2 20:56 Plex Commercial Skipper
-r-xr-xr-x   1 root  wheel   3086544 Jun  2 20:56 Plex DLNA Server
-r-xr-xr-x   1 root  wheel     62104 Jun  2 20:56 Plex Media Fingerprinter
-r-xr-xr-x   1 root  wheel   4629432 Jun  2 20:56 Plex Media Scanner
-r-xr-xr-x   1 root  wheel  15851192 Jun  2 20:56 Plex Media Server
-r-xr-xr-x   1 root  wheel   3266752 Jun  2 20:56 Plex Relay
-r-xr-xr-x   1 root  wheel      8720 Jun  2 20:56 Plex Script Host
-r-xr-xr-x   1 root  wheel      8464 Jun  2 20:56 Plex SQLite
-r-xr-xr-x   1 root  wheel    300080 Jun  2 20:56 Plex Transcoder
-r-xr-xr-x   1 root  wheel   2354640 Jun  2 20:56 Plex Tuner Service
lrwxr-xr-x   1 root  wheel        17 Jun  2 20:56 Plex_Media_Server -> Plex Media Server
drwxr-xr-x  10 root  wheel        52 Jun  4 11:11 Resources
-rw-r--r--   1 root  wheel       924 May 17 13:30 start.sh

**Comment by Winky2000** [comment]
> IF they've maintained Plex standard, /usr/lib/plexmediaserver will be where the executables are
> 
> Can you show me the contents of "COPYRIGHT" ? (It might contain something unique to TrueNAS)

A lot of what is out on the web does not match my installs. I have done a lot by trial and error and searching on my own.

**Comment by ChuckPa** [comment]
I need something to go by as a standard.

On Linux, there are a ton of docker containers.   I only acknowledge the most popular and stable ones.
I'm sure the same exists for you.

**Comment by Winky2000** [comment]
Truenas Core
https://www.truenas.com/truenas-core/
Along with official plugins
https://www.truenas.com/apps/

**Comment by ChuckPa** [comment]
I don't care if truenas PAID ME ... I have no ROOM for more STUFF     LOLOLOL
I have 7 discrete NAS boxes in my office,  plus 3 NUC ESXi boxes,  plus a mac mini and my workstation!!!  LOL

The only BSD thing I have here is pfSense  (which is good stuff).    I used to use BSD 4.x in the 1990's   :P  lol

**Comment by Winky2000** [comment]
No problem. I get it so many different things out there, hard to keep up with everything. I also have pfsense. Truenas Scale I believe runs on linux and uses a docker system. I might install that and play with it, see if your program works on it.

**Comment by ChuckPa** [comment]
If you find TrueNAS Scale w/ Linux doesn't run,  I'll definitely add it.
BSD is fighting a losing battle.

**Comment by Winky2000** [comment]
Not picking it up

root@truenas[...edia Server/Plug-in Support/Databases]# tar xf v1.0.7.tar.gz 
root@truenas[...edia Server/Plug-in Support/Databases]# cd PlexDBRepair-1.0.7 
root@truenas[... Support/Databases/PlexDBRepair-1.0.7]# chmod +x DBRepair.sh
root@truenas[... Support/Databases/PlexDBRepair-1.0.7]# ./DBRepair.sh 
Error: Unknown host. Current supported hosts are: QNAP, Syno, Netgear, Mac, ASUSTOR, WD (OS5), Linux wkstn/svr
                     Current supported container images:  Plexinc, LinuxServer, HotIO, & BINHEX

**Comment by ChuckPa** [comment]
Again,
  1.  `ls -la  /`
  2.  `cat /proc/1/cgroup`

Let's see what we have

**Comment by Winky2000** [comment]
drwxr-xr-x  21 root root   32 Jun  4 20:42 .
drwxr-xr-x  21 root root   32 Jun  4 20:42 ..
drwxr-x---   3 root root    3 Jun  4 14:24 .kube
lrwxrwxrwx   1 root root    7 Apr 10 06:56 bin -> usr/bin
drwxr-xr-x   4 root root    9 Jun  4 14:08 boot
drwxr-xr-x   3 root root    3 Apr 10 08:04 conf
-rw-r--r--   1 root root    0 Jun  5 06:44 daily_lock
drwxr-xr-x   4 root root   11 Jun  5 06:16 data
drwxr-xr-x  18 root root 3480 Jun  4 14:21 dev
drwxr-xr-x 142 root root  256 Jun  4 14:20 etc
drwxr-xr-x   4 root root    4 Jun  4 14:20 home
lrwxrwxrwx   1 root root   31 Apr 10 08:00 initrd.img -> boot/initrd.img-5.15.79+truenas
lrwxrwxrwx   1 root root   31 Apr 10 08:00 initrd.img.old -> boot/initrd.img-5.15.79+truenas
lrwxrwxrwx   1 root root    7 Apr 10 06:56 lib -> usr/lib
lrwxrwxrwx   1 root root    9 Apr 10 06:56 lib32 -> usr/lib32
lrwxrwxrwx   1 root root    9 Apr 10 06:56 lib64 -> usr/lib64
lrwxrwxrwx   1 root root   10 Apr 10 06:56 libx32 -> usr/libx32
drwxr-xr-x   2 root root    2 Apr 10 06:56 media
drwxr-xr-x   3 root root    3 Jun  4 14:19 mnt
drwxr-xr-x   4 root root    4 Jun  4 14:20 opt
drwxr-xr-x   2 root root    2 Apr 10 08:00 packages
dr-xr-xr-x 382 root root    0 Jun  4 14:15 proc
drwx------   7 root root   14 Jun  4 21:32 root
drwxr-xr-x  47 root root 1360 Jun  4 21:29 run
lrwxrwxrwx   1 root root    8 Apr 10 06:56 sbin -> usr/sbin
drwxr-xr-x   3 root root    3 Apr 10 08:05 srv
dr-xr-xr-x  13 root root    0 Jun  4 14:15 sys
drwxrwxrwt  10 root root  280 Jun  5 00:00 tmp
drwxr-xr-x  15 root root   15 Apr 10 08:04 usr
drwxr-xr-x  15 root root   18 Jun  4 14:19 var
lrwxrwxrwx   1 root root   28 Apr 10 08:00 vmlinuz -> boot/vmlinuz-5.15.79+truenas
lrwxrwxrwx   1 root root   28 Apr 10 08:00 vmlinuz.old -> boot/vmlinuz-5.15.79+truenas

0::/init.scope

**Comment by ChuckPa** [comment]
This is looking good so far.

Do you have `/usr/lib/plexmediaserver/Plex SQLite` ?

**Comment by Winky2000** [comment]
This is looking good so far.

    Do you have /usr/lib/plexmediaserver/Plex SQLite ?
    Yes

    Lastly, the full path to the databases
    /Library/Application Support/Plex Media Server/Plug-in Support/Databases

    If there's a way to start/stop PMS itself while in the container (like /plex_service.sh in the Plex image) ?
    /plex_service.sh Is that what you're looking for?

**Comment by ChuckPa** [comment]
That's exactly what I'm looking for.

All these paths should be valid for you .
If so then support is already there.

```
    elif [ -d "/config/Library/Application Support" ]; then

      PLEX_SQLITE="/usr/lib/plexmediaserver/Plex SQLite"
      AppSuppDir="/config/Library/Application Support"
      PID_FILE="$AppSuppDir/Plex Media Server/plexmediaserver.pid"
      DBDIR="$AppSuppDir/Plex Media Server/Plug-in Support/Databases"
      LOGFILE="$DBDIR/DBRepair.log"
      LOG_TOOL="logger"

      # Miscellaneous start/stop methods
      if [ -d "/var/run/service/svc-plex" ]; then
        HaveStartStop=1
        StartCommand="s6-svc -u /var/run/service/svc-plex"
        StopCommand="s6-svc -d /var/run/service/svc-plex"
      fi

      if [ -d "/var/run/s6/services/plex" ]; then
        HaveStartStop=1
        StartCommand="s6-svc -u /var/run/s6/services/plex"
        StopCommand="s6-svc -d /var/run/s6/services/plex"
      fi

      HostType="Docker"
      return 0
```

**Comment by Winky2000** [comment]
Dang if I drop it on the root / it runs on Truenas Scale. Too bad my plex is on Truenas core LOL

**Comment by Winky2000** [comment]
I think it's stuck

Automatic Check,Repair,Index started.

Checking the PMS databases
Killed
Check complete.  PMS main database is damaged.
Check complete.  PMS blobs database is OK.

Exporting current databases using timestamp: 2023-06-06_18.56.15
Exporting Main DB
command terminated with exit code 129

**Comment by Winky2000** [comment]
Finally got it to work. Copied from Core into scale then ran DBRepair.sh

Automatic Check,Repair,Index started.

Checking the PMS databases
Killed
Check complete.  PMS main database is damaged.
Check complete.  PMS blobs database is OK.

Exporting current databases using timestamp: 2023-06-06_21.30.44
Exporting Main DB
Exporting Blobs DB
Successfully exported the main and blobs databases.  Proceeding to import into new databases.
Importing Main DB.
Importing Blobs DB.
Successfully imported databases.
Verifying databases integrity after importing.
Verification complete.  PMS main database is OK.
Verification complete.  PMS blobs database is OK.
Saving current databases with '-BACKUP-2023-06-06_21.30.44'
Making repaired databases active
Repair complete. Please check your library settings and contents for completeness.
Recommend:  Scan Files and Refresh all metadata for each library section.

Backing up of databases
Backup current databases with '-BACKUP-2023-06-06_21.37.26' timestamp.
Reindexing main database
Reindexing main database successful.
Reindexing blobs database
Reindexing blobs database successful.
Reindex complete.
Automatic Check, Repair/optimize, & Index successful.

**Comment by Winky2000** [comment]
OK Now I have another problem. When I copy all databases back to core I get this message

<Response code="503" title="Maintenance" status="Plex Media Server is currently running database migrations."/>

**Comment by ChuckPa** [comment]
This is NORMAL now. 

PMS,  since 1.31.0,  has started telling us when it's running maintenance at startup INSTEAD OF making us wonder what's broken  (which has caused people prematurely restarting it and corrupting databases)

We simply wait a little bit while PMS runs its internal schema migrations (schema must match  what the code expects).

As soon as it completes,  PMS will continue normal startup/

**Comment by Winky2000** [comment]
Over 4 hours now still same thing

**Comment by ChuckPa** [comment]
Not good.   There is some deep corruption.

Take one of the backup files and shove it (and the matching blobs) into position.
Try to minimize the recovery.

**Comment by cocopuff2u** [comment]
> Finally got it to work. Copied from Core into scale then ran DBRepair.sh
> 
> Automatic Check,Repair,Index started.
> 
> Checking the PMS databases Killed Check complete. PMS main database is damaged. Check complete. PMS blobs database is OK.
> 
> Exporting current databases using timestamp: 2023-06-06_21.30.44 Exporting Main DB Exporting Blobs DB Successfully exported the main and blobs databases. Proceeding to import into new databases. Importing Main DB. Importing Blobs DB. Successfully imported databases. Verifying databases integrity after importing. Verification complete. PMS main database is OK. Verification complete. PMS blobs database is OK. Saving current databases with '-BACKUP-2023-06-06_21.30.44' Making repaired databases active Repair complete. Please check your library settings and contents for completeness. Recommend: Scan Files and Refresh all metadata for each library section.
> 
> Backing up of databases Backup current databases with '-BACKUP-2023-06-06_21.37.26' timestamp. Reindexing main database Reindexing main database successful. Reindexing blobs database Reindexing blobs database successful. Reindex complete. Automatic Check, Repair/optimize, & Index successful.

What do you mean you copied from Core to Scale? The whole database?
