### ISSUE TITLE
Kubernetes (Microk8s) Support

### ISSUE THREAD

**Issue by sgeoxd** [ChuckPa/PlexDBRepair#86]
Not so much of a bug, but awareness for a possible enhancement. At the very least, for others who encounter the same issue. While attempting to run the script on a Plex Inc. container within a Microk8s environment (instead of Docker) was encountering the following error:

> Error: Unknown host. Current supported hosts are: QNAP, Syno, Netgear, Mac, ASUSTOR, WD (OS5), Linux wkstn/svr
                     Current supported container images:  Plexinc, LinuxServer, HotIO, & BINHEX

The following code is checking specifically for Docker:
`  elif [ "$(grep docker /proc/1/cgroup | wc -l)" -gt 0 ] || [ "$(grep 0::/ /proc/1/cgroup)" = "0::/" ] ||
`

By simply modifying that line to grep for microk8s I was able to get this to run normally:
`  elif [ "$(grep microk8s /proc/1/cgroup | wc -l)" -gt 0 ] || [ "$(grep 0::/ /proc/1/cgroup)" = "0::/" ] ||
`

Identified the need to grep for microk8s by running this command noted in other posted other issues:
`root@plex-b56f7f9b-jwzf6:/PlexDBRepair-1.0.9# cat /proc/1/cgroup
12:hugetlb:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
11:rdma:/
10:devices:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
9:perf_event:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
8:pids:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
7:freezer:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
6:blkio:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
5:cpu,cpuacct:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
4:memory:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
3:net_cls,net_prio:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
2:cpuset:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
1:name=systemd:/kubepods/besteffort/podbd1d424b-7a5a-4c4d-be2d-e04edbc7f2f3/b4d34630860fd6cc820bef7481828c86e44e44dfcc9d85dfd056baf52e831d41
0::/system.slice/snap.microk8s.daemon-containerd.service
`

**Comment by ChuckPa** [comment]
I won't write here what I think you're doing / intending to do.

I don't support k8s / clustering for a reason.
