### ISSUE TITLE
Can't Stop Plex From Within Container Binhex-Unraid

### ISSUE THREAD

**Issue by joecan00** [ChuckPa/PlexDBRepair#89]
Running the binhex-plexpass instance of Plex on Unraid and whenever I run PlexDBRepair it won't let me stop Plex. I get the following option for "1". 

 1 - 'stop'      - (Not available. Stop manually)

If I stop the container it also won't work as I get the following question:

Are you trying to run the tool from outside the container environment ?

But it doesn't allow me to go further.

Any help would be greatly appriciated!

**Comment by ChuckPa** [comment]
You can't stop the container as that defeats the purpose.

BINHEX uses 'dumb-init' start  and /home/nobody/start.sh

1.  Kill -15 Plex
2.  Do what you need
3. Restart the container.

**Comment by joecan00** [comment]
Sorry if I'm not understanding, but none of the PlexDBRepair options will work because it says Plex is running. If I can't stop Plex from within the PlexDBRepair utility and I can't stop the container how do I run the PlexDBRepair functions.

I don't know what "kill -15 Plex" means.

**Comment by ChuckPa** [comment]
> I don't know what "kill -15 Plex" means.
If you don't know how to `kill -15 $(pidof 'Plex Media Server')`  then perhaps you should be using a different container which supports starting and stopping of the application and leaving the container running??

(Not trying to be harsh but this is Linux)

**Comment by joecan00** [comment]
I don't think you were trying not to be harsh.

I'm new to running Plex in a docker container on Unraid and am new to Linux. I had issues with Plex and found this utility. I couldn't get it to work so I tried asking for help. Just because I currently don't know how to use your utility or am new to something doesn't mean I should stop using Plex in a docker container on Linux.

**Comment by Sphyix** [comment]
> If you don't know how to `kill -15 $(pidof 'Plex Media Server')` then perhaps you should be using a different container which supports starting and stopping of the application and leaving the container running??
> 
> (Not trying to be harsh but this is Linux AND you're using Docker on Linux)

Please add this to the README on the docker section

**Comment by ChuckPa** [comment]
Changed
